### ISSUE TITLE
Document platformsh-examples

### ISSUE THREAD

**Issue by pjcdawkins** [platformsh/platformsh-docs#106]
Tell people what it is and what they can find there (i.e. working examples of a variety of applications)

**Comment by OriPekelman** [comment]
This should mostly live in the examples repo itself... in the READMEs .. though I would love an alltogether other solution (possibly separate repos...?).

**Comment by pjcdawkins** [comment]
I meant that people have to know that the examples are there in the first place - so we need something in the central docs.

(re. separate repos: there must have been some reason to amalgamate the repos when that was done before?)
