### ISSUE TITLE
Canada missing from Public IPs

### ISSUE THREAD

**Issue by verbeeksteven** [platformsh/platformsh-docs#1079]
Canada is missing from

https://docs.platform.sh/development/public-ips.html

I would do a PR, but I do not know all of the IPs.

**Comment by demosdemon** [comment]
inbound:

```
35.182.174.169
35.182.59.77
52.60.219.22
```

outbound

```
35.182.24.224
52.60.213.255
35.182.220.113
```

**Comment by demosdemon** [comment]
I'm like 80% sure that's right.

However, there's a 20% chance they're flipped.
