### ISSUE TITLE
Document EOL Policy

### ISSUE THREAD

**Issue by demosdemon** [platformsh/platformsh-docs#1086]
With PHP 5.6 reaching EOL, we need a blurb in our documentation with how we handle deprecated images.

As of what I know, we maintain major security updates for all images even after the deprecation.

**Comment by kaystrobach** [comment]
Esp. Interesting for migrating legacy applications, as we need to communicate clear timelines to our customers. This includes how long it’s possible to run the old application.

**Comment by Crell** [comment]
There is currently no stated policy other than "we will give ample warning before removing a container image."

**Comment by kaystrobach** [comment]
Yes and that’s the problem, if we want to migrate a legacy application we need some kind of planned timeframe, where the image is guaranteed available. Otherwise our devops will use an dedicated maschine for it, where they decide, which php version is used

**Comment by CollierCZ** [comment]
We currently state when an image is deprecated. Once it is deprecated (usually because it does not get security updates), it is no longer guaranteed to be available. There seem to be notes about this already, such as here: https://docs.platform.sh/languages/php.html#deprecated-versions
