### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by robertDouglass** [platformsh/platformsh-docs#1111]
![](/images/config_diagrams/relationships.svg)

https://github.com/platformsh/platformsh-docs/edit/master/src/configuration/app/relationships.md

**Comment by robertDouglass** [comment]
`![](/images/config_diagrams/relationships.svg)`

**Comment by chadwcarlson** [comment]
Resolved by https://github.com/platformsh/platformsh-docs/pull/1112
