### ISSUE TITLE
Improve and update Drush documentation

### ISSUE THREAD

**Issue by pjcdawkins** [platformsh/platformsh-docs#115]
* You *can* sql-sync if you have Drush >= 7 locally **and** on Platform.sh, but it requires one extra step, e.g.: https://github.com/pjcdawkins/platformsh-examples/commit/950f7cd
* Drush 7.0.0-rc2 and 8 (beta) support Drupal 8. Drush <7 **and** Drush 7.0.0 do not support Drupal 8. Any version (above 5) supports Drupal 7. But you must have the same Drush version on both local and remote environments.
* If you want to use YAML make files you will need to install Drush >=7.

**Comment by barryrld** [comment]
Bump on this. I had to submit a support request after getting errors with running sql-sync.

I've sorted our issue by adding a mount point for drush-backups.

Any chance of merging this PR in soon for https://github.com/pjcdawkins/platformsh-examples/commit/950f7cd?

**Comment by Crell** [comment]
The D7 starter kit has the drush-backups mount defined now:
https://github.com/platformsh/platformsh-example-drupal7/blob/master/.platform.app.yaml

Do we need the same on Drupal 8 as well?  That's an easy enough PR for the D8 example if so.

**Comment by barryrld** [comment]
Hi Crell. That's right we need the drush-backups mount point in the D8 version of the docs too.

I've created a PR on the platformsh-example-drupal8 repo: https://github.com/platformsh/platformsh-example-drupal8/pull/4

**Comment by Crell** [comment]
Thanks, PR has been merged.
