### ISSUE TITLE
Add limitation note of using custom domains for non-prod envs

### ISSUE THREAD

**Issue by korkhau** [platformsh/platformsh-docs#1309]
Hello.

I've tried to add a DNS domain to environment that is not production one (for my case it was QA env).
But (acc. to slack: https://platformsh.slack.com/archives/C0JHEUHQD/p1580811811077600) it is well-known limitation and it is imposible to add custom domain to environment that is not production.
Unfortunately this limitation is not highlighted in documentation at https://docs.platform.sh.
Can we have this limitation added somewhere in Domains or Routes section?

Thanks

**Comment by chadwcarlson** [comment]
Thanks @korkhau! Added.
