### ISSUE TITLE
Document support for Drupal 6, redis and cache_backport

### ISSUE THREAD

**Issue by abenamer** [platformsh/platformsh-docs#131]
I would like to write a section documenting Drupal 6, redis and cache_backport - should this be a separate section in the FAQ for redis or should I simplly append it to the D7 FAQ at https://docs.platform.sh/toolstacks/php/drupal/redis.html

**Comment by Crell** [comment]
Since Drupal 6 is now unsupported by Drupal, I don't think we need to expend any effort here.  Thank you for the offer, though!
