### ISSUE TITLE
Clarify importance of the app "name" and what it does

### ISSUE THREAD

**Issue by pjcdawkins** [platformsh/platformsh-docs#135]
See ticket `#3662`

**Comment by OriPekelman** [comment]
Is this insufficient ?
https://docs.platform.sh/user_guide/reference/platform-app-yaml.html#name

+ what we have here: https://docs.platform.sh/user_guide/reference/platform-app-yaml-multi-app.html

**Comment by pjcdawkins** [comment]
If you change the app name, your services are no longer available and thus your *data* is also not available.. and possibly it gets deleted. Not sure what happens if you change the name back - do you get your data back? if not, then the docs should state the risk.

**Comment by OriPekelman** [comment]
This sounds like  a bug. Changing an application name should have no effect on the other services running. Will confirm.

**Comment by OriPekelman** [comment]
Can not confirm this behaviour. 

Created an app with MySQL. Created table filled in data.

SSH into the prompt was: 
`web@mswy7hzcuhcjy-master--php`

Renamed app from `php` to `plop` in .platform.app.yaml (and updated routes.yaml)

SSH in, the prompt is now: 
`web@mswy7hzcuhcjy-master--plop`

Database with all the data still there.

I will now also test changing service names. That sounds like more fun.

**Comment by OriPekelman** [comment]
1. As I would have expected, changing service names make all the data go away. 
2. As I would have hoped, changing back does not bring the data back (that would be madness. We can not know what client could be mean by this)

So as far as I can see the behaviour seems sane all along . I will document the effects of changing both services and application names.

**Comment by pjcdawkins** [comment]
Well that's good, sorry false alarm- I probably misremembered hipchat comments on the subject
