### ISSUE TITLE
Backup and restore on old regions

### ISSUE THREAD

**Issue by pheadeaux** [platformsh/platformsh-docs#1409]
Hello Team,

thank you for the very good documentation!

I just ran into an critical issue: I tried to restore a branches backup to the `master`  and got the message: 

> Backups cannot be automatically restored to another environment on this region.
Please contact support.

Now I am waiting on your support in an "urgent" ticket to do something, that could have been easily timed better, if I had known.

My region is as stated in the `.project.yaml` simply `host: eu.platform.sh`
On my dashboard (https://console.platform.sh/), nearly every other project has an indication in the lower left corner, where this project is situated (e.g. "Europe EU-2"). This project has nothing.

Under "Administration > Backup and restore"

https://docs.platform.sh/administration/backup-and-restore.html#restore

it is stated:
> Be aware that the older US and EU regions do not support restoring backups to different environments. If your project is on one of the older regions you may file a support ticket to ask that a backup be restored to a different environment for you, [...]

Here is my issue:
Please outline this information more dominantly and allow the customer to understand easily, how to check for the "old" environment.

Thank you.

**Comment by chadwcarlson** [comment]
Thanks for the suggestion @pheadeaux! I've included a note in the PR above. Hope you're well!
