### ISSUE TITLE
Document adding an environment specific $cookie_domain var for Drupal installations

### ISSUE THREAD

**Issue by abenamer** [platformsh/platformsh-docs#142]
The docs should read something like:

Add an environment variable with the `drupal:` prefix on it so that it can get added to the $conf var in your Drupal installation. Example:

drupal:cookie_domain
yourdomain.com

In settings.php add this code:
if (!empty($conf['cookie_domain'])) {
    $cookie_domain=$conf['cookie_domain'];
}

**Comment by pjcdawkins** [comment]
I guess the same would apply if you wanted to set `$base_url` or `$drupal_hash_salt` or `$update_free_access` from the environment variables - would it be worth including those?

**Comment by Crell** [comment]
I believe this is mostly automatic now, if variables are named correctly.

**Comment by pjcdawkins** [comment]
To confirm: yes, it is automatic, our `settings.local.php` imports the environment variables `drupal:cookie_domain`, `drupal:installed_profile`, `drupal:drupal_hash_salt`, and `drupal:base_url` into their respective global variables.
