### ISSUE TITLE
Redirect loop and wrong link

### ISSUE THREAD

**Issue by damz** [platformsh/platformsh-docs#155]
Reported by Florian Huber:

> I have just recognized that on https://docs.platform.sh/user_guide/reference/services-yaml.html there is an wrong link to the .platform.app.yaml (used URL: https://docs.platform.sh/user_guide/reference/reference/platform-app-yaml.html).

**Comment by pjcdawkins** [comment]
fixed in https://github.com/platformsh/platformsh-docs/commit/5c9d81b4f3d9aee979262a87a691123037d02de3
