### ISSUE TITLE
Duplicate section for services

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-docs#156]
This file is not used and should probably be removed: https://github.com/platformsh/platformsh-docs/tree/master/reference/services.

This part is used: https://github.com/platformsh/platformsh-docs/blob/master/reference/services-yaml.md#supported-services

**Comment by Crell** [comment]
Were they ever used?  The information from those files would need to be ported over as appropriate before the files are purged.

**Comment by GuGuss** [comment]
This has been improved and doesn't apply anymore.
