### ISSUE TITLE
Upgrade link is broken

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-docs#157]
This link from the deprecated log message: https://docs.platform.sh/reference/upgrade/#changes-in-2015.7 is broken.

It should redirect to: https://docs.platform.sh/discover/reference/upgrade/index.html

**Comment by pjcdawkins** [comment]
Also: broken links should return a 404; they should not redirect to the homepage - this is important for SEO, and for performance if the link was to a static file (e.g. when `search_index.json` was not in the whitelist that should have given a fast 404, not a slow 301)

**Comment by OriPekelman** [comment]
Ok let's close this one and open another for "create 404 page with integrated search"
