### ISSUE TITLE
Poor search results

### ISSUE THREAD

**Issue by cs278** [platformsh/platformsh-docs#1665]
If I search on https://docs.platform.sh for "routes", I get the following results:

* https://docs.platform.sh/administration/web/configure-environment.html#routes
* https://docs.platform.sh/gettingstarted/introduction/own-code/routes-configuration.html
* https://docs.platform.sh/configuration/app/upgrading.html#platformroutesyaml
* https://docs.platform.sh/guides/gatsby/headless/drupal.html#platformroutesyaml
* https://docs.platform.sh/guides/gatsby/headless/strapi.html#platformroutesyaml
* https://docs.platform.sh/guides/gatsby/headless/wordpress.html#platformroutesyaml
* https://docs.platform.sh/guides/drupal9/deploy/configure.html#requests-configuration-routesyaml

Note the absence of the main resource on this topic: https://docs.platform.sh/configuration/routes.html

I've also tried "routes.yaml" and "configure routes" neither of which return the main routing configuration page.

The same issue appears to afflict these pages as well which seem near-impossible to locate by search:
* https://docs.platform.sh/configuration/services.html
* https://docs.platform.sh/configuration/app.html

Doing a bit of digging if I make the same search query with 1000 results limit the routes URL does not show up in the results, so perhaps it's not being indexed.

**Comment by CollierCZ** [comment]
Hi. Thanks for your patience on this issue. As part of figuring out this docs system, I think I may have stumbled on a fix for this problem. We'll test out the linked PR and hope it fixes the issue.

**Comment by cs278** [comment]
Much better :+1:
