### ISSUE TITLE
Using Redis with WordPress : Documentation outdated

### ISSUE THREAD

**Issue by manonsmnn** [platformsh/platformsh-docs#1841]
Hello,

I'm following this doc to add Redis to a Wordpress installation : https://github.com/platformsh/platformsh-docs/blob/master/docs/src/guides/wordpress/redis.md 

It seems that the package advised is old (no commit since 2019) and fetches an outdated version of the Redis Object Cache Drop-In (1.3.4), while being incompatible with newest updates of the Redis Object Cache plugin.

It was a great alternative for my website which lacks write access. I think this page should be updated or deleted, but I wanted to know if there is another package that does the same job, or another way to accomplish this ?

Thanks in advance,
Regards

**Comment by gilzow** [comment]
First, **thank you** for bringing this issue to our attention. The docs are definitely out-of-date. 

Had a chance to look into this finally. The one we suggest will still work with Redis v5 and v6. Looks like the root issue is that the suggested drop-in is constrained to v1 of composer where most have moved on to v2. We're discussing internally how we want to move forward with a suggested solution but will be updating the docs as soon as we can.

If you're already using the Redis Object Cache plugin, then you can copy in the included Redis Object Cache Drop-In fromt that plugin into wp-content. From the original docs in the [Configuration section](https://github.com/platformsh/platformsh-docs/blob/main/docs/src/guides/wordpress/redis.md#configuration), change 
```bash
hooks:
    build: |
        set -e
        bash install-redis.sh 5.1.1
        cp -r wp-content/wp-redis-object-cache-dropin/object-cache.php web/wp/wp-content/object-cache.php
```
to
```bash
hooks:
    build: |
        set -e
        bash install-redis.sh 5.1.1
        cp -r wp-content/plugins/redis-cache/includes/object-cache.php wp-content/object-cache.php
```
Adjusting the paths above to how you have your WordPress project configured.  This is obviously not a smooth developer experience, but should get you moving forward again. As I mentioned, now that we're aware of it, we'll be making changes to ensure this is much easier to implement.

Again, thank you for bringing it to our attention!
