### ISSUE TITLE
Improve the pricing page

### ISSUE THREAD

**Issue by maria-at-platform** [platformsh/platformsh-docs#1949]
Improve the general outline, style of the page. It looks like there might be inconsistencies between the main page, the marketing page and the info shown here. 

<img width="759" alt="Screenshot 2021-10-25 at 12 22 57" src="https://user-images.githubusercontent.com/90635515/138679236-292c4258-fff2-4a44-a5cc-1314f2e7a31f.png">

**Comment by trolologuy** [comment]
The page could include instructions on how to upgrade plans based on the tier.
See examples for [grid](https://github.com/platformsh/platformsh-docs/pull/2054#discussion_r840573519) and [enterprise](https://github.com/platformsh/platformsh-docs/pull/2054#discussion_r840571620).
