### ISSUE TITLE
Document environment variables labels

### ISSUE THREAD

**Issue by MariadeAnton** [platformsh/platformsh-docs#1966]
### What needs to be documented?

Customers are now able to see all variables in use for a given environment, checking their settings page.  There's a split between project and environment variables, depending on where they've been set.

[Here's one of my projects using all the options available](https://console.platform.sh/maria-de-anton/iflktnnjpggdk/activity-scripts/settings/variables). 

![image](https://user-images.githubusercontent.com/3729517/139880196-18a0dd20-9f65-479a-8f8a-b1c935e533d3.png)

`Inherited`- this variable was set on a parent environment or at the project level and the environment you're viewing is inheriting it

`Overridden` - this variable was previously  `Inherited` from an existing Project or Environment variable and its value was overridden by a new one on this specific environment. 

`Inactive` - only applies to Project Variables, if there's a variable named the same way in the environment, the environment one takes precedence and the Project one gets the `Inactive` label

### Additional context

We'd need to evaluate how this fits into our variables pages: https://docs.platform.sh/development/variables.html

**Comment by CollierCZ** [comment]
Will be done in #1976
