### ISSUE TITLE
Add cron examples for more frameworks/languages

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#1983]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/configuration/app/cron.html

### What exactly should be updated?

The only examples currently are for Drupal. It would help if there were more. Like for rake tasks in a Ruby on Rails app: `cmd: 'bundle exec rake some:task'`.

**Comment by CollierCZ** [comment]
Would be changed in location and details by #2017

**Comment by chadwcarlson** [comment]
Laravel: https://docs.platform.sh/guides/laravel/deploy/scheduling.html
