### ISSUE TITLE
Troubleshooting breadcumbs

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#1999]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/troubleshoot.html

### What exactly should be updated?

Add links to specific troubleshooting pages from general one. Make it clear to readers that we now have multiple troubleshooting pages and their specific problem might be on one of the other pages. Consider linking back to this page from that one -- just make the network of troubleshooting pages clear.

**Comment by trolologuy** [comment]
Add backlinks to specific pages (MySQL, ...)
