### ISSUE TITLE
Update timezone docs

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2046]
## Where on docs.platform.sh should be changed?

https://docs.platform.sh/configuration/app/timezone.html
https://docs.platform.sh/configuration/app/cron.html

## What exactly should be updated?

The docs should mention the possibility to set the timezone for the project (even in the console). Not just in the app settings.

This setting doesn't affect containers or logs, but does affect what times crons run.

[Additional context](https://github.com/orgs/platformsh/projects/3/views/1)

**Comment by trolologuy** [comment]
This issue will require to be careful with https://github.com/platformsh/platformsh-docs/pull/2017/files to avoid possible merge conflicts.

**Comment by trolologuy** [comment]
Currently on hold.
Clarification is needed as expected behavior does not match what the tests uncovered.

**Comment by trolologuy** [comment]
The documentation link in the console (`/<project id>/-/settings`) should point to another documentation page (TBD where exactly).
