### ISSUE TITLE
:memo: Document inactive environments

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2092]
## What needs to be documented?
 
We don't have clear docs for what inactive environments are and how to work with them. For example, if there are branches on GitHub that aren't running (such as never had a PR opened and the settings are for only PR environments to be active), users have not seen the environments in the dropdown to select environments and been confused by trying to push a branch with the same name and having it be rejected.

Make it clear what inactive environments are, how they might come to be without user action, and how to work with them. Include:

* ~Where to find them in the console~
* How to see the status of an environment
* ~How to activate in CLI/console~
* See if there's other places to link the info (like source integration)

[Additional context](https://github.com/orgs/platformsh/projects/3)

**Comment by trolologuy** [comment]
[Current page](https://docs.platform.sh/environments/deactivate-environment.html#reactivate-an-environment)

**Comment by CollierCZ** [comment]
I would say the current page is actually: https://docs.platform.sh/other/glossary.html
