### ISSUE TITLE
Drupal 7 is featured instead or Drupal 9

### ISSUE THREAD

**Issue by trolologuy** [platformsh/platformsh-docs#2119]
### Where on docs.platform.sh should be changed?

[Drupal 7 is featured](https://docs.platform.sh//frameworks/drupal7.html), whereas it's going to be [EOL at the end of the year](https://docs.platform.sh//frameworks/drupal7.html).

A [Drupal 9](https://docs.platform.sh/guides/drupal9/deploy.html) guide is already available.

### What exactly should be updated?

The Drupal 7 content might be moved elsewhere and Drupal 9 be put in the foreground?

**Comment by CollierCZ** [comment]
This should be solved by our upcoming changes to the information architecture. [Additional context](https://github.com/orgs/platformsh/projects/3)
