### ISSUE TITLE
Redis setup missing some details

### ISSUE THREAD

**Issue by sirtet** [platformsh/platformsh-docs#214]
A few issues in one:

1.
If i get it right, the redis server must also be enabled in .platform/services.yml

2.
on https://docs.platform.sh/user_guide/reference/toolstacks/php/drupal/redis-drupal-7.html
in the settings.php section it's not totally clear how this works:
Currently there's one line before the settings.local include setting which connector to use,
And then some more lines after the include. Amongst it one about the connector too, but it does not say to adjust there to the used connector, which i think i should.

3.
Can't i just as well put that code in settings.local.php to use redis eg. in production only? 
The article only promotes using environment variables for that.

4.
Also, the drupal-6 version tells how to check if redis is running, the D7 version is missing that.

**Comment by sirtet** [comment]
5.
I could not get redis running following the D6/D7 instructions.
I also needed to setup the redis relationship in .platform.app.yaml

```
relationships:
   redis: "myredis:redis"
```
Seems like another missing bit in the D6/D7 doc.

PS:
The server is answering now on the shell, but i still did not get it to work:
> Fatal error: Call to undefined function db_merge() in /app/public/includes/bootstrap.inc on line 991

**Comment by sirtet** [comment]
Ok, works now, i had a 2nd relationships- statement, which overwrote the first...

**Comment by Crell** [comment]
@sirtet So is this issue resolved then, or do you think there are specific improvements to the docs still needed?

**Comment by sirtet** [comment]
Well,my redis problems ars sloved, but i think the docs are still the same?
Sure, i would eg. add the testing- bit from D6 to the D7 page, and i think the bit about my 5. Point is also not in there...

**Comment by Crell** [comment]
Let's continue this over in the PR: https://github.com/platformsh/platformsh-docs/pull/298.  Thanks @sirtet.
