### ISSUE TITLE
🔬 Investigate where we can make the docs more generic

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2179]
We'd like to ensure the docs are welcoming of people using all sorts of frameworks and languages. Currently, some parts are focused on approaches that make sense in a PHP context, but might not elsewhere.

The goal of this issue to to define the scope of the problem and break the work down into smaller, manageable tasks. The expected outcome is a set of issues that would make the docs more welcoming.

Example: https://docs.platform.sh/development/local.html#building-the-site-locally

**Comment by CollierCZ** [comment]
Created:
- #2198
- #2199 

@trolologuy , please see
- if there's any part you can think of that's not covered in those issues (don't go through everything again, but just if you know anything)
- if the issues seem clear to you or need clarification

**Comment by trolologuy** [comment]
The example list in #2199 is already thorough. If I find other missing ones, I'll add them here.
