### ISSUE TITLE
document_root implications

### ISSUE THREAD

**Issue by hackzilla** [platformsh/platformsh-docs#220]
I was recently talking to support about why an application gets deployed into /app or sometimes /app/public

```
This is actually controlled by the document_root setting in the .platform.app.yaml. If the document_root is set to /, it will move the application to /app/public and use that as the root to allow for the private mounts to be kept private. In the case of your stats-tracking project it's doing this because there is no .platform.app.yaml so it is using the defaults.

Best,
Brad
```

This information should be added to: https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

**Comment by Crell** [comment]
I agree.  PR opened (see above). Please comment there if the additional text is sufficient.  (I based it on the support comment above.)  Thanks!
