### ISSUE TITLE
Multi app config + git submodules

### ISSUE THREAD

**Issue by drublic** [platformsh/platformsh-docs#225]
When testing git submodules with a multi application setup as described [here](https://github.com/platformsh/platformsh-docs/blob/master/reference/platform-app-yaml-multi-app.md#file-structure) I had several issues which were not easy to debug.
When I removed the git structure with submodules and commited all files to the main directory instead of submodules it was possible to push the application.

Maybe this is a bug or git submodules do not work with multi apps.
It is also possible that I did some configs wrong which would be odd since it works with the same configs when not using submodules.

The error:

```
Validating configuration files.
E: Error parsing configuration files:
   - http://docs.{default}/: Upstream 'docs:php' of route 'http://docs.{default}/' doesn't exist.
To 63nps64z7mely@git.eu.platform.sh:63nps64z7mely.git
```

**Comment by sruggier** [comment]
Yes, we currently have a limitation that although the applications can be in the submodules, the .platform.app.yaml files have to be in the top-level repository (someone else ran into this issue at around the same time you did). This is a bug that we intend to fix at some point. For now it would make sense for us to mention this in the documentation, which seems to strongly imply that there are no limitations.

**Comment by drublic** [comment]
Thanks for the feedback.

As this does not work as I expected it too here is a quick outline on what I currently have to do to work around that issue: I had to setup a separate repository which is build by a CI tool which clones all the submodules I need, checks it into a branch and pushes the branch to Platform.sh.
This does not make it easily possible to get different environments.
There are other problems that come up with this behavior.

Do you have any other suggestion to work around this?
Is there a timeframe on when this will be fixed?

**Comment by sruggier** [comment]
Yeah, you could also work around this by moving the .platform.app.yaml files into the top-level repository. Then you'd include the submodules in directories alongside the .platform.app.yaml files, and then adjust the document root to point to the submodules' web root relative to each .platform.app.yaml file.

For example, your directory tree could look like this:
```
.git/
.platform/
    routes.yaml
    services.yaml
app1/
    .platform.app.yaml
    app1-submodule/
        index.php
app2/
    .platform.app.yaml
    app2-submodule/
        index.php
```

and then in app1's .platform.app.yaml file, you could include:
```
web:
    document_root: "/app1-submodule"
    # Or /app1-submodule/path/to/webroot if appropriate.
    passthru: "/index.php"
```

I realize this is a pain in comparison to how it should work, and I'm sorry for that, but it might at least be easier than what you're doing, if it doesn't break your workflow to have the .platform.app.yaml files separated like that.
