### ISSUE TITLE
📝 Clarify how to use Varnish

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2355]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/configuration/services/varnish.html
https://docs.platform.sh/bestpractices/http-caching.html

### What exactly should be updated?

People have been confused about how to set up Varnish and how to purge the cache (see context).

Rework the page so it's clear what to do with Platform.sh. Don't get into too many details about Varnish itself, which should be covered by Varnish docs.

Update for:

-  Content accuracy
-  Includes what it should
-  Doesn't include what doesn't fit
-  Fits template
-  Fits style guide

**Comment by aikaterine** [comment]
It is critical here for you to be clear that your solution:

1. Opens up the possobility for any project hosted on the same server to clear the cache (call with external URL), or
2. Requires protecting the purging with ip addresses, and/or token

None of those are ideal and if a project wants the ability to purge uising Varnish (which, lets be honest, most do) then their options at platform.sh are problematic and burdensome (to be nice). Odds are that projects which require push based caching will need to incur additional expense with Cloudflare or Fastly to get what should be provided out of the box with platform. sh. 

Particularly galling is the line:

"Generally speaking, you should use Varnish only if your application requires push-based clearing or relies on Varnish-specific business logic."

You don't actually support that in a safe manner. It is misleading, at best.

**Comment by CollierCZ** [comment]
Thanks for the feedback, @aikaterine. We'd definitely like to stop clear up any places that might be misleading.

The solution proposed internally so far seemed to be using a token. I haven't looked into the details yet myself (since I haven't gotten to the task yet). Do you have particular concerns that would make the token not a good route to take?

**Comment by letharion** [comment]
The issue I see with a token is that it changes the implementation from being completely standard, as in, something you can copy from the docs, to entirely bespoke. That also appears to be the opposite of the desire of this ticket, as the description says:

> Don't get into too many details about Varnish itself, which should be covered by Varnish docs.

But this approach won't be covered by varnish docs. I haven't seen this done elsewhere, so integrations to varnish, in our case a Drupal-module, will need to be adapted in addition to the custom varnish logic be written. Overall it will make everything more complicated, for the "gain" of working around a limitation in the platform services specification.

**Comment by CollierCZ** [comment]
Unfortunately, it doesn't seem like we'll be able to fix the underlying issue to make this easy any time soon. I've added your feedback to our internal tracker, which I hope will help push it up the priority list. But the standard way doesn't seem likely in the immediate future. I'm still working on finding the best other way to do it.

**Comment by aikaterine** [comment]
Thank you for keeping on top of this.

**Comment by CollierCZ** [comment]
That's what I'm trying to figure out now. The person who has had ideas on it is out now, but I hope to get some answers when they get back.

**Comment by aikaterine** [comment]
Awesome, thank you. We are looking at implementing this solution as a stop-gap to wait for something more standard so would be good to have insight :)

**Comment by letharion** [comment]
FWIW this varnish build appears to include relevant functionality: https://github.com/wodby/varnish
As far as I can tell it's not part of a stock varnish build though.

**Comment by CollierCZ** [comment]
So it seems like the plan to make environment variables available to services has not worked out as planned. It is possible to hardcode a token in the VCL, but not access environment variables. There's a record of wanting to make this possible (whether through setting environment variables or using relationships), but it's not implemented and won't be in the immediate future.
