### ISSUE TITLE
Add a glossary of terms

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-docs#236]
I recall seeing a sentence somewhere in the platform.sh docs which said something like "If the project has a project file then the project will be built in project mode", which was very confusing.

Project seems to be used as a verb and an adjective, and in any case it's a standard English word which has broader meanings outside of platform.sh

If we had a glossary, project, project file, project mode could have their own entries.

**Comment by kotnik** [comment]
Actually we do have a [glossary](https://docs.platform.sh/user_guide/GLOSSARY.html) ([source](https://github.com/platformsh/platformsh-docs/blob/master/GLOSSARY.md)). What you are right about is that we should broaden that up, to explain the Platform.sh lingo.

**Comment by fuzzbomb** [comment]
Oh it turns out there was a lot more but it was removed.

https://github.com/platformsh/platformsh-docs/commit/b61b8b1c8d6706c6a62099aec2ea366bab1ddf25#diff-b375e0ff7c51891627c7bf8142a4abeb

**Comment by fuzzbomb** [comment]
The FAQ has some definitions in it. Project is defined, but that doesn't help with building 'in project mode'. Wish I could find that phrase again.

**Comment by sruggier** [comment]
@fuzzbomb: Were you thinking of [this page](https://docs.platform.sh/user_guide/reference/toolstacks/php/drupal/index.html)?
