### ISSUE TITLE
Collapsible table of contents is hard to discover due to low contrast icon.

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-docs#237]
Developers over the age of 40 (or so) need to be able to read the user guide ;-)

The burger button in the top-left is coloured #ccc on a white background, so it's hard to know that a table of contents is available. Additionally it has a low-contrast focus outline (also #ccc).

Can we darken this to at least #757575 so it passes WCAG AA contrast requirements?

**Comment by OriPekelman** [comment]
Agreed. It took me time to find the hamburger even when I knew I was supposed to look for it. Anyway we should be redesigning this soon..
