### ISSUE TITLE
Clarify how to contribute

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-docs#238]
The section in the README about conributing to the documentation doesn't make sense.

- It talks about Symfony documentation
- The link "Contributing to the Documentation" just leads to docs.platform.sh, and I can't find anything there about contributing.

**Comment by sruggier** [comment]
Hmm, that's embarrassing! I'm not sure how that happened (even after looking at the commit history), but I've removed the reference to Symfony and rewritten the Contributing section. I couldn't find any existing guidelines in the repository, so I just kept it short and sweet. Thanks for reporting this!
