### ISSUE TITLE
📝 Improve get started docs

### ISSUE THREAD

**Issue by trolologuy** [platformsh/platformsh-docs#2402]
We'd like to improve the getting started flow to make it shorter and clearer for new users.

We'll focus on people who have code already, assuming that's the main use case. Can offer links to starter sites for specific stacks. Not Platform.sh templates, as those already include the  Platform.sh-related files. The end of the tutorial would be more like what the templates are.

**Comment by CollierCZ** [comment]
We already have items for tracking this.
