### ISSUE TITLE
📝 Support for custom additional hosts

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-docs#2415]
### What needs to be documented?

Our upcoming Git release will add support for custom additional hosts in `.platform.app.yaml`.

This new `additional_hosts` key is a mapping of hostname to IP address to be added to the container's hosts file. This allows users to define custom entries in `/etc/hosts` for their applications.

### Usage

```
additional_hosts:
  foo.example.com: "1.1.1.2"
  foo2.example.com: "1.1.1.1"
```

### Additional context

Update app reference.

**Comment by lolautruche** [comment]
We need to make it clear that only IPv4 addresses can be used here.
