### ISSUE TITLE
📝 Rework region migration

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2418]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/projects/region-migration.html

### What exactly should be updated?

Update for:

- Content accuracy
- Includes what it should
- Doesn't include what doesn't fit
- Fits template
- Fits style guide

Ensure reasons for migration are up to date. Including what a legacy region is.

**Comment by platformbill** [comment]
Perhaps https://docs.platform.sh/development/regions.html should also have a "what is a legacy region" type section.

**Comment by CollierCZ** [comment]
Thanks for the note, @platformbill! Added it as part of #2434
