### ISSUE TITLE
📝 Add availability details for the regions

### ISSUE THREAD

**Issue by trolologuy** [platformsh/platformsh-docs#2426]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/regions.html

### What exactly should be updated?

- The region list should only include public regions.
- Regions marked as legacy should have their names changed
- Add a note about how region availability depends on org settings
- Regions that are not publicly available without specific settings should be marked as such in the list (or mark the others as "available to new organizations" or something similar)
- Consider changing the order of the list and other changes to make it clearer what's available and what is a priority.

**Comment by JGrubb** [comment]
So, we actually have this in the warehouse internally, I don't know if an embed of this report is an option or not 

https://dash.pltfrm.sh/public/question/3061e2de-c8a9-4d1e-bbd4-e292c1eb2011

**Comment by CollierCZ** [comment]
Thanks for the report, @JGrubb! I think we'll not embed directly so we can add context, but it's definitely useful.
