### ISSUE TITLE
🐛 eu-4 region availability

### ISSUE THREAD

**Issue by raupie** [platformsh/platformsh-docs#2454]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/regions.html#europe

### What exactly should be updated?

The eu-4 region is closed. Yet the configuration says `availability: false`

https://github.com/platformsh/platformsh-docs/blob/main/docs/data/regions.yaml#L34

So bug? :bug:

**Comment by CollierCZ** [comment]
Was a miscommunication with what an empty cell meant.
