### ISSUE TITLE
amqp not supported on PHP 8.0

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#2464]
### Where on docs.platform.sh should be changed?

Extensions table in https://docs.platform.sh/languages/php/extensions.html

### What exactly should be updated?

amqp + 8.0 should be either removed, or this is an unexpected gap that needs to be fixed in the image (tested on project in eu-3)

### Additional context

```
 Found 1 new commit
 
 E: Error parsing configuration files:
    - applications: Uncaught exception: The "amqp" extension is not supported for php:8.0
        at <script>:101:0
          throw("The \"" + unsupported_extensions[0] + "\" extension is not supported for " + service.type);
          ^
 
 E: Error: Invalid configuration files, aborting build
```

**Comment by CollierCZ** [comment]
It's supported at least now.
