### ISSUE TITLE
🐛 Issue on the page Use Lando for local development

### ISSUE THREAD

**Issue by kopeboy** [platformsh/platformsh-docs#2483]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/local/lando.html

### What exactly should be updated?

No mention of Platform.sh access token, which is requested in terminal as soon as I try to start Lando with `lando init --recipe platformsh --source cwd`

What should I put there?! Thank you

**Comment by kopeboy** [comment]
I tried pasting my project id but I'm still stuck here
<img width="679" alt="image" src="https://user-images.githubusercontent.com/4728367/182421477-b711bf60-7e47-4c48-9637-44536efde900.png">

**Comment by CollierCZ** [comment]
Sorry to see that. Thanks for reporting! We'll try to get it fixed soon. In the meantime, it's probably one of these tokens: https://docs.platform.sh/development/cli/api-tokens.html
