### ISSUE TITLE
📝 Update DDEV docs for Platform integration

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2486]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/local/ddev.html

### What exactly should be updated?

[New integration](https://github.com/platformsh/ddev-platformsh) will automatically configure more things so users don't have to do as much. Docs should make note of this.

As a part of this, also look into making it clearer that DDEV is the recommended local development option -- because the integration is smoother than any other option. Possibly separating into categories (such as `Integrated location development` and `Supported environments`) or something else that differentiates it.

### Additional context

See Context for thoughts on recommendation

**Comment by lolautruche** [comment]
It also implies updating the [doc page on DDEV website](https://ddev.readthedocs.io/en/stable/users/providers/platform/) (it might point to our own doc page, WDYT @rfay?)
[Source is here](https://github.com/drud/ddev/blob/master/docs/content/users/providers/platform.md).

**Comment by rfay** [comment]
The DDEV docs already point to the integration, the tip early on https://ddev.readthedocs.io/en/latest/users/providers/platform/ - I'm not sure whether more is warranted?

**Comment by lolautruche** [comment]
@rfay I'd prefer if the doc pointed to the appropriate page on docs.platform.sh

**Comment by rfay** [comment]
Ah, I didn't understand. That's easy. When the docs are ready, just click the pencil in the upper right of the page. 

However... it then means we have so many parallels docs, but I guess that's the way it is.

**Comment by lolautruche** [comment]
Maybe we can remove the current doc we have in DDEV and instead point to our docs

**Comment by rfay** [comment]
It's better to maintain things in only one place, but since all other upstream integrations are described in the DDEV docs, I don't see "removing" as a good option. However, trying to focus people to the Platform.sh docs would be fine.

Note that the Platform.sh integration is used by lots of people who will never use the add-on, and it's a fundamental part of core DDEV.
