### ISSUE TITLE
Uninherited variables when renaming the default branch

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#2504]
### Where on docs.platform.sh should be changed?

- https://docs.platform.sh/environments/default-environment.html#1-create-the-main-environment
- https://docs.platform.sh/environments/default-environment.html#1-create-the-main-branch

### What exactly should be updated?

If a production-only environment variable is set (`--inheritable=false`), and the steps in this guide are followed, the "new" production environment will potentially not receive important credentials during the switch (as an example, `FASTLY_API_TOKEN`). 

So as an update, I can think of two options
- A warning: place a note in each of these sections, letting users know of this gotcha.
- A script: sort of a force inherit script, that loops through production environment variables, setting them in the `main` environment.

**Comment by CollierCZ** [comment]
Good timing! We had this idea (though with less detail) as part of #2375, which I'm starting work on today. So hopefully this will be fixed by early next week.

**Comment by chadwcarlson** [comment]
Related:

- it may be necessary to enable emails on the "new" prod environment manually (since they are disabled by default on dev environments) before the switch
