### ISSUE TITLE
🐛 Issue on the page Configure DNS

### ISSUE THREAD

**Issue by clundquist-stripe** [platformsh/platformsh-docs#2561]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/gettingstarted/next-steps/going-live/configure-dns.html

### What exactly should be updated?

> Add a CNAME record from your desired domain (and it’s www subdomain) to the value of the edge_hostname

You can't have a CNAME next to an SOA record, and an apex domain should have an SOA record.

Alias A records are a work around, but often don't work across providers.

https://www.ietf.org/archive/id/draft-sury-dnsext-cname-at-apex-00.html#RFC1034
never made it out of draft

**Comment by CollierCZ** [comment]
Thanks for the note, @clundquist-stripe 

@trolologuy, have a look at this as part of #2447
