### ISSUE TITLE
The advice regarding using --iconv=utf-8-mac,utf-8 should be qualified

### ISSUE THREAD

**Issue by xendk** [platformsh/platformsh-docs#2581]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/tutorials/migrating.html

### What exactly should be updated?

Regarding `rsync` it states:

> If you're running rsync on MacOS, you should add --iconv=utf-8-mac,utf-8 to your rsync call.

This should be qualified, as it might not always be the case. We had a tar file of files from a Drupal site, where the files were using `a%CC%8A` (urlencoded for clarity, "a" + COMBINING RING ABOVE) for `å` rather than `%C3%A5` (LATIN SMALL LETTER A WITH RING ABOVE). The latter is commonly used in UTF-8, while the former is the one preferred by OSX. Drupal don't care, as long as the filename matches the entry in the `file_managed` table, but rsync'ing the files with `--iconv=utf-8-mac,utf-8` would "fix" the files to canonical UTF-8, causing Drupal to not being able to find the file.

There will be cases where the conversion is desired, but as the above shows, the recommendation should be somehow qualified as to when it might apply.

**Comment by CollierCZ** [comment]
Original issue was #421.

Hope to fix it in #2577
