### ISSUE TITLE
New CLI installation process

### ISSUE THREAD

**Issue by lolautruche** [platformsh/platformsh-docs#2598]
### What needs to be documented?

The new CLI is replacing [the legacy one](https://github.com/platformsh/platformsh-cli/). As such, we need to update the install documentation wherever the old installer or its requirements are mentioned, including:
* [Getting Started - Import your own code](https://docs.platform.sh/gettingstarted/introduction/own-code/cli-install.html)
* [Getting Started - Start with a template](https://docs.platform.sh/gettingstarted/introduction/template/cli-install.html)
* [Use the command line](https://docs.platform.sh/administration/cli.html)
* [PHP CLI Readme](https://github.com/platformsh/platformsh-cli#user-content-installation)
* Setup Wizard
![image](https://user-images.githubusercontent.com/313528/193781963-7943bfa4-ecec-44b7-ac0b-2233aeb4d9cb.png)

* "Install CLI" link in the console (currently pointing to https://github.com/platformsh/platformsh-cli)
  
![image](https://user-images.githubusercontent.com/313528/193781546-1df65348-34a5-46e5-8219-d2b7b3207896.png)

### Additional context

The new CLI must be installed using [Homebrew](https://brew.sh) (macOS / Linux / WSL) or [Scoop](https://scoop.sh/) (Windows):

```bash
# macOS / Linux / WSL using Homebrew
brew install platformsh/tap/platformsh-cli
```

```powershell
# Windows using Scoop
scoop bucket add platformsh https://github.com/platformsh/homebrew-tap.git
scoop install platform
```

* All upgrades must be done using the same channel (`self:update` is now disabled):
  * `brew upgrade platformsh-cli` (macOS / Linux / WSL)
  * `scoop update platform` (Windows)
* We need to make it clear that we're now using [Homebrew](https://brew.sh) for macOS (Intel and M1/M2), Linux (amd64 and ARM), Windows using WSL (then the same method than for Linux applies) or [Scoop](https://scoop.sh/) (traditional Windows).
* It's still possible to [download the binary](https://github.com/platformsh/homebrew-tap/releases/latest) and install it manually (we also offer `.deb`, `.apk` and `.rpm` files)
* We may still offer the possibility to install the legacy CLI as an alternative if any blocking issue appears
* For now we host the binaries on the [Homebrew Tap repository](https://github.com/platformsh/homebrew-tap), but this will change for the RC. [The new CLI repository](https://github.com/platformsh/cli) will be used instead.

**Comment by lolautruche** [comment]
@CollierCZ We will finally go for a public beta, so we'll need to maintain install docs for both versions during that time.
However, I think we should still advertise the new version more, like "Here's how you install the (new) version. Oh, if you still want to install the old one, you may do it this way"

**Comment by CollierCZ** [comment]
Makes sense. We can include the new version in a variety of places and link to the old version in one.

**Comment by lolautruche** [comment]
I updated the description according to the most recent changes
