### ISSUE TITLE
📝 Update activity scripts reference

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2608]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/integrations/activity/reference.html

### What exactly should be updated?

Different activities have different payloads and properties. This means the reference isn't accurate or complete and it's hard to use activity scripts.

Update the activity scripts reference so it follows the reference template and general style and is accurate and complete.

**Comment by CollierCZ** [comment]
The new version of the API server will include a `--result` filter. Should probably include that here, depending on how long it takes to come out.

**Comment by trolologuy** [comment]
To get the full list for the reference, check the code or do a script which logs all the values.
