### ISSUE TITLE
📝 Document flexible resources

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2620]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/overview/pricing.html
https://docs.platform.sh/increase-observability/metrics.html
And elsewhere

### What exactly should be updated?

The upcoming release of flexible resources means how we document plans and resource usage.

**Comment by chadwcarlson** [comment]
Related (follow-up) issue: https://github.com/platformsh/platformsh-docs/issues/2573
