### ISSUE TITLE
Documentation is wrong regarding MySQL 5.5 -> MariaDB 10.0

### ISSUE THREAD

**Issue by Jamesking56** [platformsh/platformsh-docs#2683]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/add-services/mysql.html

### What exactly should be updated?

Configuring your service to this:

```
main:
    type: mariadb:5.5
    disk: 2048
```
```
relationships:
    dbmain: "main:mysql"
```

Causes no relationship to show on Platform.

Trying:

```
relationships:
    dbmain: "main:mariadb"
```

Crashes the entire environment, causing a ticket needing to be raised to fix it.

The documentation is not clear on what you should be using, in the end this appears to work:

```
main:
    type: mysql:5.5
    disk: 2048
```
```
relationships:
    dbmain: "main:mysql"
```

And gives MariaDB 5.5 - Note how its not even MySQL here.

The documentation states:

> If you change the service type, your data is removed.

But this is simply not true, switching from `mysql:5.5` to `mariadb:10.0` retains the data in the database. 

### Additional context

This caused us a lot of confusion and it was clear from others in Slack that the relationships and services configuration is confusing to them to. The documentation needs to be clearer on what you should put in the `relationships` key in `.platform.app.yaml` to avoid environment crashing - crashed environments cost us a day of work.

**Comment by CollierCZ** [comment]
I'm sorry to see that you lost work on this. I know that can be frustrating.

Version 5.5 is one of the deprecated versions. I know that has caused problems for people with other services, so it's possible that was part of the issue here. Does it work for you with one of the [supported versions](https://docs.platform.sh/add-services/mysql.html#supported-versions)?

**Comment by AnouckColson** [comment]
Obsolete, doc has been updated since.
