### ISSUE TITLE
Review and update Get started tutorial

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#2783]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/get-started/add-data.html

https://docs.platform.sh/get-started/monitor-and-troubleshoot.html

### What exactly should be updated?

The flow of the tutorial seems to be confusing for some readers, maybe we can have a look at it again and see if it could be improved.

The **Monitor and troubleshoot** section may be in need of an update. We had a request to add information about metrics, Blackfire, health alerts for disk. Let's have a look, keeping in mind that this is a Get started tutorial so it shouldn't be overcrowded with information.

Check information related to stacks is up-to-date, especially Java (see Context).

**Comment by CollierCZ** [comment]
The original comments related to overview pages that shouldn't be entryways into the tutorial. If people enter that way, I'd prefer for them not to see information. If we get similar comments from actual readers, we can reopen this.
