### ISSUE TITLE
Adjust simplified theme

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#2785]
### Where on docs.platform.sh should be changed?

Docs site theme.

### What exactly should be updated?

The theme of the docs site [has been simplified](https://github.com/platformsh/platformsh-docs/pull/2768/files) to make the future redesign by the Design team easier to implement.

Let's log all the feedback that's coming our way regarding this temporary theme, and see if there's a quick way to fix not-so-ideal elements before the actual redesign is carried out. See context for more information on each request.

-  Reduce white space in between elements in the docs.
-  Remove inactive scrollbar next to in-page navigation links.

**Comment by CollierCZ** [comment]
These will be decided during the upcoming design work. For now, added to the list in #2186
