### ISSUE TITLE
Library not loaded: openssl@1.1

### ISSUE THREAD

**Issue by cobadger-aten** [platformsh/platformsh-docs#2828]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/administration/cli.html

### What exactly should be updated?

Provide steps to diagnose and correct the problem in which platformsh-cli returns the error
`dyld[4563]: Library not loaded: /opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib`.

### Additional context

Randy Fay helped me on Platforsh Slack this afternoon diagnosing and correcting this problem on my Mac. He thought it might be helpful to document this in case other users experience the same problem.

Some months ago I got a new Macbook Pro with an M1 chip and I migrated everything over from my non-M1 machine using Apple's migration tool. If I remember correctly, something that I had installed in my non-M1 machine wasn't working at the command line on my new machine, and I tried using Rosetta as a workaround.

It was a successful workaround for months.

For no reason that I could discern, platformsh-cli abruptly stopped working for me: any `platform` command would report the error shown above. No amount of repairing, uninstalling and installing platformsh-cli and openssl@1.1 solved the problem.

**Comment by rfay** [comment]
Can you please update the OP more explaining your experience and how you got there, and what you had to do to fix it?

**Comment by cobadger-aten** [comment]
@rfay Updated.
