### ISSUE TITLE
Add 2022 Transparency Report

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#2927]
### What needs to be documented?

As is listed for previous years, we need to add the 2022 transparency report at https://docs.platform.sh/security/transparency.html. 

### Additional context

See Context & [process context](https://github.com/platformsh/platformsh-docs/pulls?q=is%3Apr+transparency)

**Comment by AnouckColson** [comment]
Link to the report : https://docs.google.com/document/d/1fWeRKO7uMJBXCexxG-PfAtabNlOK6TKvOghkC_im9iw/edit

**Comment by chadwcarlson** [comment]
I have a PR in progress for this one, just trying to figure out what's changed in the styles behind PDF generation, which don't quite work how they used to.

**Comment by chadwcarlson** [comment]
Print styles re-added in https://github.com/platformsh/platformsh-docs/pull/2934
