### ISSUE TITLE
Splunk integration improvements

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#2992]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/increase-observability/logs/forward-logs.html#integrated-third-party-services

### What exactly should be updated?

There has been customer feedback that the Splunk integration page is written incorrectly/does not work. More details to come.

**Comment by gilzow** [comment]
currently shows
```
platform platform integration:add --type splunk --url https://http-inputs.HOST.splunkcloud.com/services/collector/event --index INDEX --token TOKEN
```
one of the two `platform` need to be removed.
