### ISSUE TITLE
Make backup and restore information clearer

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3019]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/environments/backup.html

https://docs.platform.sh/environments/restore.html

### What exactly should be updated?

People get consistently confused about whether code is included in a backup/restore. 
Let's make things as clear as possible based on feedback in Context.

**Comment by Mupsi** [comment]
We were told about a `restore_code` parameter that allows to restore the data AND the code at once (https://api.platform.sh/docs/#tag/Environment-Backups/operation/restore-backup). However after a few tests, Anouck and I noticed that despite being present in the API, this argument is not supported by either the CLI or the Console. So for now it's pretty clear that we should not imply that the code will be restored; maybe remove language like "snapshot" as it may give the impression that the code will also be reverted automatically.
