### ISSUE TITLE
Manage Node.js Versions for Runtime Containers

### ISSUE THREAD

**Issue by soleson** [platformsh/platformsh-docs#3051]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/nodejs/node-version.html

### What exactly should be updated?

The instructions for using the specified Node version (as set via NVM) in the runtime container (script via `.environment`) assume that the `$PLATFORM_APP_DIR/.nvm` directory exists in runtime. However, the preceding instructions suggest building and activating the Node.js version within `$PLATFORM_CACHE_DIR/.nvm` (cache) and then creating a symlink between the application directory and the cache directory: `ln -s $PLATFORM_CACHE_DIR/.nvm $NVM_DIR `.

The symlink is broken because the cache directory does not exist in the runtime container. As such, the Node.js version is not changed in the runtime container.

### Additional context

Perhaps the content of the `$PLATFORM_CACHE_DIR/.nvm` needs to be copied into a local directory instead of using a symlink.

**Comment by chadwcarlson** [comment]
@gilzow Does this look correct to you for this one?
