### ISSUE TITLE
Environments built from forks cannot receive new commits

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#3061]
### Where on docs.platform.sh should be changed?

https://github.com/platformsh/platformsh-docs/blob/main/.github/workflows/build-from-fork.yaml

https://github.com/platformsh/platformsh-docs/blob/0d86c2ce1a4c2faaa5cf04ed3d6130323031a4f2/.github/workflows/build-from-fork.yaml#L27-L47

### What exactly should be updated?

Testing the current situation is explained in https://github.com/platformsh/platformsh-docs/pull/3060.

Essentially,

- pull requests from **forks** are not built when opened
- the environment must manually be triggered, by 1) adding the `build-fork` label to the PR, then 2) rerunning the "Build from fork" and "Get info on PR" jobs for a successful deployment.
- the "Build from fork" job is accomplished the deployment by first creating a new branch using the Pull request number as a name (`pr-XXXX`), and then manually activating that branch on the Platform.sh project.
- There is not enough time between creating the branch and the activation command - P.sh is not yet aware of `pr-XXXX`'s existence, so "Build from fork" fails the first time around (which causes "Get info on PR" to fail).
-  After completing all of the above, we have an environment associated with `pr-XXXX`, which is a copy of the state of `forking-user:forking-user-patch-X` **when the `build-fork` label is added**. 
- As a consequence, any new commits pushed to `forking-user:forking-user-patch-X` **are not** reflected on `pr-XXXX` OR on its pull request environment.

**Comment by gilzow** [comment]
This should now be resolved via #3087 and #3088
