### ISSUE TITLE
[Bug] PR environments from forked repos are not deleted from Platform.sh

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#3070]
### Where on docs.platform.sh should be changed?

https://github.com/platformsh/platformsh-docs/blob/8bd60af2326704beea9897cefbe1efc9c027ae47/.github/workflows/build-from-fork.yaml#L31

https://github.com/platformsh/platformsh-docs/blob/8bd60af2326704beea9897cefbe1efc9c027ae47/.github/workflows/manage-environment.yaml#L61 

### What exactly should be updated?

Due to the way the platform.sh GitHub integration is currently implemented, branches that are named `pr-##` are not deleted from the Platform.sh side when the `prune_branches` option is set to `true`. Since we are controlling the generation of these branches from a workflow (see above), we should use a different prefix to designate our PR branches.

**Comment by gilzow** [comment]
Missed one:

https://github.com/platformsh/platformsh-docs/blob/8bd60af2326704beea9897cefbe1efc9c027ae47/.github/workflows/get-pr-info.yaml#L39

**Comment by gilzow** [comment]
Since this branch name prefix is used in multiple workflows, my suggestion would be to set it as a repository variable that we could then reference. This would also allow us to change it more easily if we discover we need to later on. 

ie `BFF_PREFIX=bffpr` or something similar?
(**B**ranch**F**rom**F**ork_PREFIX=**b**ranch**f**rom**f**ork**p**ull**r**equest ) 

cc @chadwcarlson / @AnouckColson

**Comment by chadwcarlson** [comment]
I like it 👍
