### ISSUE TITLE
[Enhancement] dynamically retrieve platform.sh project ID

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#3090]
### Where on docs.platform.sh should be changed?

https://github.com/platformsh/platformsh-docs/blob/1d13e7fa9586e1bd0d341803ce13be09c632de8a/.github/workflows/build-from-fork.yaml#L10 
https://github.com/platformsh/platformsh-docs/blob/1d13e7fa9586e1bd0d341803ce13be09c632de8a/.github/workflows/get-pr-info.yaml#L9 
https://github.com/platformsh/platformsh-docs/blob/1d13e7fa9586e1bd0d341803ce13be09c632de8a/.github/workflows/get-pr-info.yaml#L111
https://github.com/platformsh/platformsh-docs/blob/1d13e7fa9586e1bd0d341803ce13be09c632de8a/.github/workflows/manage-environment.yaml#L12 

### What exactly should be updated?

Platform.sh project ID is hard-coded into three separate workflow files. We should either make, and then reference, a single repository variable, or alternatively, use the [Platform.sh Retrieve Project ID](https://github.com/platformsh/gha-retrieve-projectid) github action. 

### Additional context

It's entirely possible that we'll need to move the project to a new region in the future, and in doing so, the project ID will change. This will minimize the fallout from any such move.

**Comment by chadwcarlson** [comment]
This has been solved, and is retrieved from a variable. https://github.com/platformsh/platformsh-docs/blob/15352ec0e505dd174877f5f76da8a0decf443d59/.github/workflows/build-from-fork.yaml#L10
