### ISSUE TITLE
Document how to restart PHP-FPM with admin agent

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3155]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/php/tuning.html#restart-php-fpm

### What exactly should be updated?

Keep in mind that the admin agent should provide a way to Interact with systemd services (start/stop/restart/tail journal).
When the feature is ready, it should be documented for e.g. how it can be used to restart PHP-FPM. Check the rest of the docs to see if other related updates are warranted/if we need to add content to fully document this feature.

See context.

**Comment by chadwcarlson** [comment]
Internal only, closing.
