### ISSUE TITLE
Links in activity response are undefined

### ISSUE THREAD

**Issue by kksandr7** [platformsh/platformsh-docs#3161]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/integrations/activity/reference.html

### What exactly should be updated?

The full activity response to a Git push does not contain `"_links": ...`. I don't get these values, no conditions for their availability are specified.

### Additional context

https://github.com/platformsh/platformsh-docs/blob/main/docs/src/integrations/activity/reference.md?plain=1#L615

**Comment by chadwcarlson** [comment]
Hi @kksandr7! Thanks for reporting - closing this issue since `_links` has since been restored to `/environments/ENV_ID/activities/ACTIVITY_ID`.
