### ISSUE TITLE
Git set executable file permission on Windows

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3163]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/guides/drupal9/deploy/configure.html and check if it might be applicable to other places in the docs.

### What exactly should be updated?

To be able to execute scripts such as the `platformsh_deploy_drupal.sh` one, Windows users may need to run [a particular Git command](https://www.scivision.dev/git-windows-chmod-executable/) beforehand. Add a note about this to the docs. See context for screenshots of the original customer request.

**Comment by chadwcarlson** [comment]
- you may need to `chmod +x the script`
- though we recommend ... (paul's recommendation)

**Comment by chadwcarlson** [comment]
Placed on https://docs.platform.sh/development/troubleshoot.html#command-not-found
