### ISSUE TITLE
local builds dont have PLATFORM_CACHE_DIR

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#3169]
### Where on docs.platform.sh should be changed?

n/a

### What exactly should be updated?

It's great that we're caching retrieved files into the build cache; it definitely speeds up the builds. BUT, local users don't have that environmental variable defined, causing the whole script to come c(r)aching down. 

We need to come up with something that will create the caching space locally if we determine they're not running the scripts in a platform.sh build environment.

**Comment by gilzow** [comment]
should we either:

1. Only use cache if we're in a platform environment?
2. have a fallback location if `PLATFORM_CACHE_DIR` is not set. If we pick this one, where should the location be?

also opened to a 3rd, 4th, etc options if someone can think of something

**Comment by chadwcarlson** [comment]
I think 1 is the simplest. Otherwise, gitignoring a `docs/cached_files` seems fine.
