### ISSUE TITLE
Document Elasticsearch Enterprise

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3210]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/add-services/elasticsearch.html

### What exactly should be updated?

Elasticsearch Enterprise is going to be available to Enterprise clients, so it needs to be reflected in the docs.

**Comment by remilejeune2** [comment]
- Elasticsearch Enterprise is similar to Mongod Enterprise : https://docs.platform.sh/add-services/mongodb.html, it's a premium service which require an extra cost.
- All free versions are deprecated, the paid versions are the only one maintained.
- We support: 7.17 and 8.5 on Grid. 8.5, 7.17 on DG2, no support on DG3
- To use the service, the type is `type: elasticsearch-enterprise:7.17`
