### ISSUE TITLE
Multi-app doc improvement

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#3235]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/create-apps/multi-app.html
https://docs.platform.sh/development/submodules.html

There is 2 different pages regarding submodules, one for single app and another for multi-app (and no link between them)

  

### What exactly should be updated?

# For https://docs.platform.sh/development/submodules.html

1. Clone submodules during deployment
https://docs.platform.sh/development/submodules.html#clone-submodules-during-deployment
if you just write this `.gitmodules` file with content from the doc, 
```
[submodule "app/Oro"]
	path = src/Oro
	url = https://github.com/orocrm/platform.git
[submodule "src/OroPackages/src/Oro/Bundle/EntitySerializedFieldsBundle"]
	path = src/OroPackages/src/Oro/Bundle/EntitySerializedFieldsBundle
	url = https://github.com/orocrm/OroEntitySerializedFieldsBundle.git
[submodule "src/OroB2B"]
	path = src/OroB2B
	url = https://github.com/orocommerce/orocommerce.git
```
you will get an error while deploying
```
Found 1 new commit

E: Error parsing configuration files:
    - applications: Unable to find source folder 'admin/admin-submodule' for application defined in '/admin/.platform.app.yaml', check the 'source.root: <root>' line in this file.

E: Error: Invalid configuration files, aborting build
```
as it seems that there is no action on git side to pull those submodules.
Instead of writing it manually, we need to use this git command : 
```
git submodule add --name "app/Oro" https://github.com/orocrm/platform.git "src/Oro"
git add .
git commit -m "adding app/Oro submodule"
platform push 
```

2. Removing submodules
https://docs.platform.sh/development/submodules.html#removing-submodules
```
git submodule deinit -f src/Oro
    Cleared directory 'src/Oro'
    Submodule 'app/Oro' (https://github.com/orocrm/platform.git) unregistered for path 'src/Oro'
git rm -r --cached src/Oro
git commit -m "Removed submodule."
rm -rf path_to_submodule
```

3. maybe we need to group those 2 doc pages into one, or add a link from each other to the other. 

# For https://docs.platform.sh/create-apps/multi-app.html

I try it first using submodules at the root of my sources. 

## Submodules at the root of the project

this project is using submodules at the root of sources

https://console.platform.sh/devrel-projects/a6b3w26i7qioe/multiapp-finished-submodules

with Git repo : 

- [main repo](https://github.com/platformsh-templates/bigfoot-workshop-with-api/tree/multiapp-finished-submodules)
- [Admin submodule repo](https://github.com/platformsh-templates/bigfoot-workshop-with-api-admin)
- [API submodule repo](https://github.com/platformsh-templates/bigfoot-workshop-with-api-api)
- [Gatsby submodule repo](https://github.com/platformsh-templates/bigfoot-workshop-with-api-gatsby)
- [Mercure submodule repo](https://github.com/platformsh-templates/bigfoot-workshop-with-api-mercure)

### to add them, i just did : 
```
git submodule add --name admin https://github.com/platformsh-templates/bigfoot-workshop-with-api-admin.git admin
git submodule add --name mercure https://github.com/platformsh-templates/bigfoot-workshop-with-api-mercure.git mercure
git submodule add --name api https://github.com/platformsh-templates/bigfoot-workshop-with-api-api.git api
git submodule add --name gatsby https://github.com/platformsh-templates/bigfoot-workshop-with-api-gatsby.git gatsby
git add .
git commit -m "adding submodules" && git push
platform push
```
and it generates the right `.gitmodules` file with four entries.

### Update each submodules 
```
cd admin && git pull origin main && cd ..
cd api && git pull origin main && cd ..
cd gatsby && git pull origin main && cd ..
cd mercure && git pull origin main && cd ..
git add .
git commit -m "update submodules from upstream"
platform push 
```

### Some tips

- each submodule repo needs to have its own `.platform.app.yaml` file into it

pro/con:
- as each submodule repo have their own `.platform.app.yaml`, it seems much easier for each member of the dev team to manage the way his stack needs to be deploy.

## Submodules in a subfolder of each app folder (same as described in the doc)

This environment is having subfolder in each app folder:

https://console.platform.sh/devrel-projects/a6b3w26i7qioe/multiapp-submodules-subfolders

with Git repo : 

- [main repo](https://github.com/platformsh-templates/bigfoot-workshop-with-api/tree/multiapp-submodules-subfolders)
- [Admin submodule repo](https://github.com/flovntp/bigfoot-workshop-with-api-admin)
- [API submodule repo](https://github.com/flovntp/bigfoot-workshop-with-api-api)
- [Gatsby submodule repo](https://github.com/flovntp/bigfoot-workshop-with-api-gatsby)
- [Mercure submodule repo](https://github.com/flovntp/bigfoot-workshop-with-api-mercure)

Note: Each of the forks have the same sources but without the `.platform.app.yaml` file

to add all submodules, i used : 
```
git submodule add --name admin https://github.com/flovntp/bigfoot-workshop-with-api-admin.git admin/admin-submodule 
git submodule add --name api https://github.com/flovntp/bigfoot-workshop-with-api-api.git api/api-submodule 
git submodule add --name gatsby https://github.com/flovntp/bigfoot-workshop-with-api-gatsby.git gatsby/gatsby-submodule 
git submodule add --name mercure https://github.com/flovntp/bigfoot-workshop-with-api-mercure.git mercure/mercure-submodule 
git add .
git commit -m "adding submodules" && git push
platform push
```

### Update each submodules 
```
cd admin/admin-submodule && git pull origin main && cd ../..
cd api/api-submodule && git pull origin main && cd ../..
cd gatsby/gatsby-submodule && git pull origin main && cd ../..
cd mercure/mercure-submodule && git pull origin main && cd ../..
git add .
git commit -m "update submodules from upstream"
platform push 
```

pro/con
- all PSH related files are in the same repo, so easier to manage from a devOps perspective (but harder from a dev perspective if i need to change a deploy hook by adding a new command line for example

In any case, it's not convenient to update upstream sources, maybe we need an easier way to do so but maybe it's because i'm not a git submodule expert (ping @gilzow ?)

**Comment by gilzow** [comment]
I think there are a couple of things compounding the confusion, though given submodules are an advanced git concept, that's not surprising.  

On the current [Using Git submodules](https://docs.platform.sh/development/submodules.html) page, it is showing an _example_ `.gitmodules` file contents. You can't just create that file and commit it; you have to add git submodules via the `git submodule add` command. That is _implied_ on the page, but not necessarily spelled out directly. In addition, the example we've used is more complex and using something (OroCRM) most users are probably not familiar with. If they're _also_ not familiar with git submodules, the example can be rather difficult to understand. 

In order to make this an understandable _example_, then it probably needs to be part of a larger tutorial where we build to this step. Alternatively, we could use the [submodules example from the Hugo template](https://github.com/platformsh-templates/hugo/blob/master/.gitmodules), and before showing the contents of the .gitmodules file, explain what it's doing. Alternatively, we could link to the [Git docs on submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and say something like 

> After adding your git submodules according to your project layout, and committing the relevant changes, when you push to Platform.sh, the system will try to clone your submodules. Given the following example submodule layout 
`<example-gitmodules-file>`
If we then run `git push`, you will see the output of the log:
`<sample-log-output>`

I do find it interesting we've included instructions for removing git submodules on this page, but don't include something similar for adding git submodules... 🤔 

I'm not in complete agreement with combining the two docs pages into one, since you can use submodules without using them for a multiapp, which is what the [Using Git submodules](https://docs.platform.sh/development/submodules.html) page is addressing. Though adding some links between the two is always a good idea. 

As for updating, you can use the `git submodule update` command to perform pulls for you, so you don't have to go into each one idividually. 
`git submodule update --remote` Will `pull` for all submodules. 
`git submodule update --remote <submodule-name>` will only pull for the submodule specified by `<submodule-name>`

**Comment by flovntp** [comment]
Hi @gilzow 

I just finish to setup the [Bigfoot multi-app project](https://console.platform.sh/florent-huckatplatform-sh/2t52epxgzt4d4) with 3 environments, to reflect what could be done with multi-app, using 3 different approachs: 
- `main` : multi app with submodules (containing the `.platform.app.yaml` file) at the root of the sources
- `multiapp-subfolders-applications`: with submodules (that does not contains `.platform.app.yaml` file) at the root of the sources BUT with the `.platform/applications.yaml` file 
- `multiapp-submodules-subfolders`: with `.platform.app.yaml` in app subfolder and submodules in a subfolder of the app folder (same as currently described in the multi-app doc page)

note: This bigfoot Multi-app is the multi-app that the DevRel team design for @Mupsi's talks at Symfony Online: Bigfoot + API Platform v3 + Gatsby frontend + Mercure server. 

my preference here is the structure of the `multiapp-subfolders-applications` branch, with `.platform/applications.yaml` file in the main repo. 
As @chadwcarlson said, if the `.platform.app.yaml` is in the submodule repo, it could leads the dedicated dev of the submodule thinking that they can create a single project from the submodule sources and it's not ideal from my point of view.

**Github structure:**
- [main github repo](https://github.com/platformsh-templates/bigfoot-multiapp)
- [submodule `admin`](https://github.com/platformsh-templates/bigfoot-multiapp-admin) (API Platform Admin component)
    - branch `with-platform-app-yaml` that contains `.platform.app.yaml` file
    - branch `without-platform-app-yaml` that doesn't contain `.platform.app.yaml` file 
- [submodule `api`](https://github.com/platformsh-templates/bigfoot-multiapp-api) (Symfony Bigfoot)
    - branch `with-platform-app-yaml` that contains `.platform.app.yaml` file
    - branch `without-platform-app-yaml` that doesn't contain `.platform.app.yaml` file 
- [submodule `gatsby`](https://github.com/platformsh-templates/bigfoot-multiapp-gatsby) (Gatsby frontend)
    - branch `with-platform-app-yaml` that contains `.platform.app.yaml` file
    - branch `without-platform-app-yaml` that doesn't contain `.platform.app.yaml` file 
- [submodule `mercure`](https://github.com/platformsh-templates/bigfoot-multiapp-mercure) (Mercure rocks server)
    - branch `with-platform-app-yaml` that contains `.platform.app.yaml` file
    - branch `without-platform-app-yaml` that doesn't contain `.platform.app.yaml` file 

note: if you change branch locally, you will need to run `git submodule update --remote` as it seems that submodule folders are not well changed when switching branches... 

@gilzow from your previous comment: 

ok for not merging those 2 pages (multi-app and gitsubmodules), i agree, 2 different subjects here.

From the actual doc, I tried to add those OroPlatform submodules in a Symfony 5.4 with success but then leads to an unexpected error on Symfony side (issues on this Oro submodule with some interface names that are not correct!?), so i don't know if it's relevant to keep an example that is not working... 
or maybe you know how to make it works locally? 

And big thanks for the trick `git submodule update --remote` to update all submodules at once, it was what i expected from you, my git master ;) 

Let's have a discussion about this to decide which source structure we want to show in the multi-app doc.

**Comment by gilzow** [comment]
First, excellent job, @flovntp, on building all of this and documenting it! 

Second, I was not aware that platform.sh would build a project where there was no platform.sh configuration file present in the project, but n+1 config files _are_ present in submodules. This approach is not currently documented. Or maybe it **is** but it's _implied_?

> In this setup, your app configuration has to be in the top repository, not in a submodule. In this case, and any other case where you want the configuration to be separate from the code, you need to specify the code root in the configuration file.

Maybe the intent here was to say that you _can_ have the app configuration in the repo for the code, but if you don't want to do it that way, you can _also_ separate the two? 

So then, as you said, we have 3 different methods of building a multiapp with git submodules:
1. Each sub app is a submodule that has its own subdirectory, where the psh config file for that app is in the subdirectory ([currently documented](https://docs.platform.sh/create-apps/multi-app.html#configuration-separate-from-code-git-submodules))
2. Each sub app is a submodule that has its own subdirectory, but a unified configuration file is used ([also documented](https://docs.platform.sh/create-apps/multi-app.html#unified-app-configuration), but not necessarily in the context of using it with submodules) 
3. Each sub app contains its psh configuration file in its own repo, and a parent repo contains each sub app as a submodule in the root, with only the psh `routes.yaml` and `services.yaml` in the parent repo (not documented)

Personally, I think #1 is the most self-explanatory, but we should probably make sure all three options are documented.

**Comment by gilzow** [comment]
As for which one should we use for a multi-app demo, until Git 22.7 is rolled out to all regions, deploying a _new_ instance of the template from the console will fail. We may just need to include a section in the README that list which regions it will/won't work on.
