### ISSUE TITLE
Update Drupal 9 guide to Drupal 10

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3237]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/guides/drupal9/deploy.html 

### What exactly should be updated?

See when we can address this once Marine has bandwidth.

**Comment by chadwcarlson** [comment]
The path has been updated from `drupal9` to `drupal`, and all external resource links and snippet examples have been updated to Drupal 10.
