### ISSUE TITLE
Update Ruby page irt versions

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3243]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/ruby.html

### What exactly should be updated?

We might need to add a Deprecated section like some other pages in the docs as we have customers still on EOL versions. 

Also the [template on the page](https://docs.platform.sh/languages/ruby.html#project-templates) isn't in a currently supported version (says 2.6 but it's really 2.7 which is EOL). So we need to update the template or remove it, to discuss with team.

**Comment by remilejeune2** [comment]
Deprecated versions are:
2.3, 2.4, 2.5, 2.6 and 2.7.
Both on Grid and DG3.
