### ISSUE TITLE
Add info on Git limitations

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3254]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/troubleshoot.html ? TBD

### What exactly should be updated?

We need to add some info in the docs about Git limitations that can impact performance and cause issues with the Console. We could suggest rebasing/squashing commits strategy for troubleshooting or as a best practice (discuss with team).

See context.

**Comment by chadwcarlson** [comment]
Potential place to judge if troubleshooting approach is needed - needs verification:

```
$ platform project:curl -p 652soceglkw4u | jq '.status'
{
  "code": "provisioned",
  "message": "ok"
}
```

I believe either `code` or more likely `message` will be `dirty` in the state described in the ticket.

**Comment by AnouckColson** [comment]
Create page in Best Practices section to help users keep their repository clean => need access to Zendesk ticket again to get details on how Support handled the situation with a real customer. Add note on each integration page to elaborate on why `prune-branche` should be enabled + add link to Best practices page.
