### ISSUE TITLE
🐛 Issue on the page Set variables | Platform.sh Docs

### ISSUE THREAD

**Issue by pbowyer** [platformsh/platformsh-docs#3271]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/variables/set-variables.html#create-project-variables

### What exactly should be updated?

It would be really helpful - like would have saved me 1.5hrs of going in circles helpful - if this page mentioned that for variables to be exposed as environment variables you need to prefix the variable name with `env:`. 

It's used in the example at https://docs.platform.sh/development/variables/set-variables.html#example-environment-variable but that wasn't enough. It wasn't until I found https://docs.platform.sh/development/variables.html#top-level-environment-variables and read the bit I quote below that I got the "aha" moment of why I couldnt' see the environment variables I'd created.

> By default, project and environment variables are only added to the `$PLATFORM_VARIABLES` environment variable. You can also expose a variable as its own environment variable by giving it the prefix env:.

Once I added `env:` to the variable names it all worked...

**Comment by chadwcarlson** [comment]
Thanks @pbowyer for the feedback, and sorry you got caught up on that one. We've tried to make that note clearer in https://github.com/platformsh/platformsh-docs/pull/3272.
