### ISSUE TITLE
Enable Heap in Vendorized Documentation

### ISSUE THREAD

**Issue by tylers-username** [platformsh/platformsh-docs#3334]
### Where on docs.platform.sh should be changed?

n/a - not docs related

### What exactly should be updated?

We should carry the work done in [this MR](https://github.com/platformsh/platformsh-docs/pull/2808) into our vendorized documentation to ensure that we can learn more about documentation usage while ensuring that documentation users are 100% anonymized—protecting their privacy.

We should attempt to carry this into [this mr](https://github.com/platformsh/platformsh-docs/pull/3328).

**Comment by chadwcarlson** [comment]
For primary and vendorized documentation, the HEAP_ID can be kept the same. All filtering happens on the Heap dashboard side. 

That said, there are changes to be made to the current implementation to clean up the theme:

- [ ] Remove [hard-coded value](https://github.com/platformsh/platformsh-docs/blob/main/docs/themes/psh-docs/layouts/partials/scripts/external.html#L14), move to project variable on Platform.sh side

**Comment by chadwcarlson** [comment]
Resolved in https://github.com/platformsh/platformsh-docs/pull/3614
