### ISSUE TITLE
deploy friday still using platform.sh meta elements

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#3341]
### Where on docs.platform.sh should be changed?

All pages

### What exactly should be updated?

the `meta description`, `meta twitter:*`, and `meta og:*` related elements are all still using the Platform.sh values.

Examples:
```
  <meta name="description" content="Platform.sh is a second-generation...
  <snip>
  <meta name="twitter:title" content="Platform.sh User Documentation">
<snip>
    <meta property="og:site_name" content="Platform.sh User Documentation">
```

**Comment by chadwcarlson** [comment]
This has now all been updated as of the friday/upsun rename (`view-source:https://docs.upsun.com/`) and can be closed.
