### ISSUE TITLE
Double quote in PR title cause env build to fail

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#3413]
### Where on docs.platform.sh should be changed?

when having double quote in a PR title, during the GH workflow, we set the PSH env title to the PR title and if having double quote, it leads to an unexpected error
```
prTitle=The premium-feature add-on banner title should be called "Premium Service" rather ' than "Beta"
```
error: 
```
Notice: Updating Platform.sh environment title for better tracking...
/home/runner/work/_temp/86a20ffd-be3e-40db-ab11-36851bfb56be.sh: line 33: Service rather than Beta: command not found
```

### What exactly should be updated?

We should escape double quote from the PR title before set it to the env

**Comment by gilzow** [comment]
Issue still not corrected. Reopening to refactor
