### ISSUE TITLE
Update info on PLATFORM_SMTP_HOST variable

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3435]
### Where on docs.platform.sh should be changed?

We need to update the docs for that environmental variable to indicate it is not present in the environment if the setting for email has been disabled for the environment.

### What exactly should be updated?

https://docs.platform.sh/development/email.html#5-send-email-from-your-app
and possibly https://docs.platform.sh/development/variables/use-variables.html#use-provided-variables

see context

**Comment by chadwcarlson** [comment]
On the two pages linked, it appears that this change has already been applied:

First,

```
When outgoing emails are on, PLATFORM_SMTP_HOST is the address of the SMTP host that should be used. When outgoing emails are off, the variable is empty.
```

and second,

```
The SMTP host to send email messages through. Is empty when mail is disabled for the current environment.
```
