### ISSUE TITLE
Document automatic resources allocation when Git24 would be rolled out

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#3497]
### Where on docs.platform.sh should be changed?

allocation resources with all the way to allocate resources

### What exactly should be updated?

referring to this [conversation](https://platformsh.slack.com/archives/C04UN8KU5UP/p1696865200223039), 
To sum it up:

- `git push upsun <branch>` --> use default resources
- `git push upsun <branch> -o resources.init=minimum` --> use minimum resources
- `git push upsun <branch> -o resources.init=parent`  --> use parent resources (should always be the case if env has a parent?)
- `git push upsun <branch> -o resources.init=manual`  --> raise an error and ask to execute `resources:set`  command (or use `-o resources.<label>` on next push to set resources)

there is also the non required option `-o resources.init=default` that is available (if we want to be explicit).

**Comment by thomasdiluccio** [comment]
This update should be made once Git24 is fully rolled out.

**Comment by chadwcarlson** [comment]
Closed with https://github.com/platformsh/platformsh-docs/pull/3564
