### ISSUE TITLE
Push options: resources.init

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#3526]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/environments.html#push-options
https://docs.upsun.com/environments.html#push-options

### What exactly should be updated?

Git 24 introduced a new push-option `resources.init` to define which strategy to use on push, possible strategies are:

- `manual`: fail the deployment and ask the user to configure the resources manually.
- `minimum`: initialize new apps and services with the minimum required resources.
- `default`: initialize new apps and services with a default amount of resources.
- `parent`: initialize new apps and services using the parent environment sizes with a fallback to default.

**Comment by AnouckColson** [comment]
Addressed in #3579
