### ISSUE TITLE
Add service page for Clickhouse

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3538]
### What needs to be documented?

A new Clickhouse 23 image was released. We need to add it to our `registry.json`, but we also need a matching service page. 
Communication with @remilejeune2 has started on this, awaiting his info on this + see existing thread in Context.

**Comment by remilejeune2** [comment]
It requires a beta flag, HA and upgrade path are uncleared.

Support version

- 23 on Grid only

Relationship reference

```bash
{
      "username": "main",
      "fragment": null,
      "ip": "169.254.143.42",
      "cluster": "s7vj2hgh6nwsk-main-bvxea6i",
      "host": "clickhouse.internal",
      "path": "main",
      "query": {
        "is_master": true
      },
      "password": "63f06c05a632f9e66be25b51cde5c573",
      "port": 9000,
      "host_mapped": false,
      "service": "clickhouse",
      "hostname": "oid3uu43xj2iujgwvplpo6ytme.clickhouse.service._.eu-3.platformsh.site",
      "epoch": 0,
      "instance_ips": [
        "247.95.64.160"
      ],
      "rel": "clickhouse",
      "scheme": "clickhouse",
      "type": "clickhouse:23",
      "public": false
    }
```

1. Configure the service

```bash
clickhouse:
  type: clickhouse:23
  disk: 256
```

1. Add the relationship

```bash
relationships:
  clickhouse: "clickhouse:clickhouse"
	OR  
	clickhouse: "clickhouse:clickhouse-http"
```

All network ports [[listed here](https://clickhouse.com/docs/en/guides/sre/network-ports)](https://clickhouse.com/docs/en/guides/sre/network-ports) can be used, we explicitly support these two: 

`clickhouse` : Native Protocol port (also referred to as ClickHouse TCP protocol). Used by ClickHouse apps and processes like `clickhouse-server`, `clickhouse-client`, and native ClickHouse tools. used for inter-server communication for distributed queries.

`clickhouse-http`: HTTP API Port for http requests. used by JDBC, ODBC and web interfaces.

Default database is “main”

**Comment by AnouckColson** [comment]
Q: only Upsun or also PSH?

**Comment by remilejeune2** [comment]
> Q: only Upsun or also PSH?

Upsun only. Clickhouse requires a lot of memory and won't fit on a standard dev plan.

**Comment by chadwcarlson** [comment]
Closed by https://github.com/platformsh/platformsh-docs/pull/3720
