### ISSUE TITLE
Activating an environment is missing from the doc

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#3560]
### Where on docs.platform.sh should be changed?

As using a source integration or pushing directly to PSH/Upsun repo is not activating the corresponding env, we should add a section here to mention it and change page name to `Activate/Deactivate an environment` 

https://docs.upsun.com/environments/deactivate-environment.html

### What exactly should be updated?

adding a section for activating an env at the beginning of the page

**Comment by chadwcarlson** [comment]
I think we should keep the current title for now, and we reference activation at the bottom of thepage https://docs.upsun.com/environments/deactivate-environment.html#reactivate-an-environment
