### ISSUE TITLE
add property `max_connections` to mariadb service page

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#3666]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/add-services/mysql.html#configure-the-database

### What exactly should be updated?

looks like a property `max_connections` has been added and no one told us. Integer. Unsure of min, max, and defaults.

see thread in #platformsh-docs for more information.

**Comment by chadwcarlson** [comment]
![CleanShot 2024-04-16 at 10 54 11](https://github.com/platformsh/platformsh-docs/assets/5473659/939c4aef-4e8f-47bd-8dcb-28b73b28b1ca)


```latex
\text{int}\left[ \min \left( \frac{\text{FREE_MEMORY}}{\text{max_allowed_packet}}, 500 \right) \right]
```
