### ISSUE TITLE
Add `container_profile` first level keys

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#3698]
### Where on docs.platform.sh should be changed?

https://docs.upsun.com/create-apps/app-reference.html#primary-application-properties

### What exactly should be updated?

we need to add a new `container_profile` key in the Upsun reference table 

i also as add it in this [platformify PR](https://github.com/platformsh/platformify/pull/194/files)

**Comment by chadwcarlson** [comment]
Dependent on further conversation related to Upsun resourcees.
