### ISSUE TITLE
revert extension change from .md to .html

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#3729]
### Where on docs.platform.sh should be changed?

for this [PR](https://github.com/platformsh/platformsh-docs/pull/3697) to pass check on internal links, i needed to change template extension from `.md` to `.html`, even if the file exists.
* https://github.com/platformsh/platformsh-docs/pull/3554/files#diff-72e78960d783f0559be934f4cc61cd39e5c3060d977f4659c77bf4af3564db99R40
* https://github.com/platformsh/platformsh-docs/pull/3554/files#diff-72e78960d783f0559be934f4cc61cd39e5c3060d977f4659c77bf4af3564db99R42

### What exactly should be updated?

change 
```
destination="/create-apps/app-reference.html"
```
to 
```
destination="/create-apps/app-reference.md"
```

**Comment by chadwcarlson** [comment]
This issue is a reminder to reinstate or test the original `md` formatting once the two vendors (Platform.sh and Upsun) have been separated from one another.

**Comment by chadwcarlson** [comment]
Closing this issue, as it's just a specific example of the larger task of moving check-links to the Upsun docs, like they are for the Platform.sh docs.
