### ISSUE TITLE
Platform Reference Links Tree Broken.

### ISSUE THREAD

**Issue by chriscalip** [platformsh/platformsh-docs#378]
404
https://docs.platform.sh/reference/cache/#enable-http-caching
This link is reference at : 
https://platform.sh/blog/new-features/
HTTP caching
Read more about configuring the cache on our documentation.

404
https://docs.platform.sh/reference

**Comment by Crell** [comment]
Hm. That blog post is quite old.  I'm not sure if we want to go through and modify old blog posts.  The most common pages already have temporary redirects, but I'm skeptical about setting up permanent redirects for old blog posts or modifying old posts.  That strikes me as revisionist history. :smile: 

Thoughts?

**Comment by chriscalip** [comment]
Right my entry point was using google to figure out if platform.sh uses varnish. This post was the top link.
Looking at docs, https://docs.platform.sh/configuration/routes/cache.html , provides the main cache mechanism. 
Revisionist history? not really, its more of making it easy for new users to get the information.

**Comment by GuGuss** [comment]
I'm in favor of documenting how Platform.sh caching strategy over-rule most of Varnish features.

**Comment by Crell** [comment]
@GuGuss That's not really relevant to this issue (nor is it true).  This is just about a now-broken link from an old blog post.  Do we modify the old blog post or no?
