### ISSUE TITLE
cron running on dash shell

### ISSUE THREAD

**Issue by hanoii** [platformsh/platformsh-docs#381]
l just found out that a command that worked fine on `platform ssh` was not working on cron, by looking at cron.log I found out that it was run on dash, so I fixed it accordingly.

This should be documented probably on the cron section, that is run with `dash` and that you can use that shell within the container to try it out.

**Comment by Crell** [comment]
Good catch. I've filed a PR at #411 to clarify this and a few other points.  Let's continue/review there.
