### ISSUE TITLE
PHP: mcrypt included by default or not?

### ISSUE THREAD

**Issue by themrwilliams** [platformsh/platformsh-docs#388]
Looking at https://docs.platform.sh/languages/php.html, it's indicated that mcrypt is "enabled by default".  However, when tinkering with Platform.sh I found that I had to specify it explicitly (was using PHP 7.0) or I got an error when Composer ran about mcrypt not being available.

I'd be happy to correct the docs via a PR, but I'm not sure whether this is a bug in the platform or the docs.

Relevant tidbits:
```
          - cakephp/cakephp 2.8.6 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.

        To enable extensions, verify that they are enabled in those .ini files:
          - /etc/php/7.0/cli/php.ini
        You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

Fixed by adding the following to `.platform.app.yaml`
```
runtime:
    extensions:
        - mcrypt
```

**Comment by Crell** [comment]
It looks like it's enabled by default pre-7.0.  As of PHP 7 it's not enabled by default.  That's following upstream recommendations from the PHP team, as mcrypt is going to be deprecated in PHP 7.1 and removed thereafter: https://wiki.php.net/rfc/mcrypt-viking-funeral.  The extension itself is unmaintained and insecure, so CakePHP really should stop using it.

That said, we ought to update the docs as well to indicate that it's only enabled on 5.6 and lower (as we do with a few other extensions).  Do you want to file a PR or should I?
