### ISSUE TITLE
Rework Build and Deploy page to include `pre_start`command

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3937]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/learn/overview/build-deploy.html

### What exactly should be updated?

Further information on the `pre_start` command is needed (similar to the info provided on each hook in the table on https://docs.platform.sh/create-apps/hooks/hooks-comparison.html). There is confusion as to how it works and where it belongs in the whole build and deploy flow, so we need to make that clear.

Atm we only have mention of the `pre_start` command on https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook with a link to the configuration side on https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#web-commands .

### Additional context

See thread for screenshots with client questions/showing the confusion.

_No response_

**Comment by chadwcarlson** [comment]
A typical example would be to regenerate / warm up cache

```yaml
web:
    commands:
        pre_start: 'bash warmup-cache'
```

**Comment by fabpot** [comment]
> A typical example would be to regenerate / warm up cache
> 
> ```yaml
> web:
>     commands:
>         pre_start: 'bash warmup-cache'
> ```

Be careful here as the `pre_start` hook is not blocking, which means that the `deploy` hook can start running before the `pre_start` command is finished.
