### ISSUE TITLE
run a Runtime operation from the console

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#4149]
### What needs to be documented?

It seems that we don't have any description on how to run a runtime operation from the console, something similar to [source operation](https://docs.upsun.com/create-apps/source-operations.html#run-a-source-operation)

**Comment by Kemi-Elizabeth** [comment]
Just for added context, this is the page I'm changing: https://docs.platform.sh/create-apps/runtime-operations.html#run-a-runtime-operation

**Comment by Kemi-Elizabeth** [comment]
All done!
