### ISSUE TITLE
swap steps 5 & 6 in the change default/production branch section

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#4180]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/environments/default-environment.html
https://docs.upsun.com/environments/default-environment.html

### What exactly should be updated?

Current step 5 should become step 6; current step 6 should become step 5.

You have to set the new default branch property (current step 6) before you can deactivate the "old" default branch (current step 5).

**Comment by Kemi-Elizabeth** [comment]
All done!
