### ISSUE TITLE
Review and clarify how to set up a new domain name and DNS records

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-docs#420]
The documentation for how to set up a domain name for a site is slightly confusing and could do with a tidy.

**Comment by pjcdawkins** [comment]
Yup, and it hardcodes things like `<environment>-<project>.<region>.platform.sh`, which is not strictly correct - it doesn't consider multi-app projects, and it isn't helpful WRT the environment machine names (https://platform.sh/2016/08/gitflow-is-now-supported/).

**Comment by pjcdawkins** [comment]
Maybe we need a CLI command?
```
platform just-show-me-my-cname
```

**Comment by xtfer** [comment]
I think @pjcdawkins has the right idea... I ran into problems halfway through when I discovered I couldn't configure my CNAME against an IP address. The requirement to have an Alias or "ANAME" capable provider should be first, since thats going to be the first hurdle.

**Comment by Crell** [comment]
I've a PR in progress to gut and overhaul the Go Live docs.  Feedback welcome: #472

**Comment by Crell** [comment]
Also, related Jira tickets (for internal use): https://platformsh.atlassian.net/browse/PF-2581

**Comment by Crell** [comment]
Closing in favor of #472
