### ISSUE TITLE
rsync from MacOS to application container may get wrong file name

### ISSUE THREAD

**Issue by mrkschan** [platformsh/platformsh-docs#421]
See http://serverfault.com/questions/638316/rsync-iconv-option-on-mac-not-working-sync-from-remote-linux-server-to-local#639367

If the file name is having unicode character and running rsync without `--iconv=utf-8-mac,utf-8` will get wrong file name on the application container.

This issue is recently hit by a customer. Shall we add a note to our rsync examples?

**Comment by Crell** [comment]
Yes, sounds like something to add to the import/export pages.  Do you want to do the PR or shall I?
