### ISSUE TITLE
Improvements to Dedicated docs 

### ISSUE THREAD

**Issue by Kemi-Elizabeth** [platformsh/platformsh-docs#4221]
### Where on docs.platform.sh should be changed?

DG2/DG3 docs will be improved according to plans outlined in this spreadsheet: https://docs.google.com/spreadsheets/d/1XUaNbDgEu-6VUfbu9Gk2nQc7k7uuUBBa7qbSTL86Fpo/edit?gid=0#gid=0

### What exactly should be updated?

https://docs.platform.sh/dedicated-gen-2/overview.html
https://docs.platform.sh/dedicated-gen-3.html

New pages will be added to these sections with another higher level that provides an overview for the Dedicated offering overall.

**Comment by gilzow** [comment]
Adding one comment outside my review since it covers all the changed files: we should replace the absolute URL links with relative links so the links go to the correct locations in preview environments.

**Comment by gilzow** [comment]
Another general comment: We seem to flip between "Development environment(s)" and "Development Environment(s)" and I can't tell if there's a specific logic to when one is used vs the other.

**Comment by gilzow** [comment]
Another one: we seem to flip between the term "autonomous" (dedicated environments overview) and "Self-service via yaml config files" (DG3 / DG2 overviews). We should be consistent across them.

**Comment by Kemi-Elizabeth** [comment]
Thanks Paul! All the inconsistencies regarding Autonomous and Dedicated Environments have been solved. In the docs, I've set it so we only capitalize the E in Dedicated Environments if it's in direct relation to Dedicated. If we're referencing development, production, staging or anything else then the E is lower case. I've also changed Autonomous to self-service.
