### ISSUE TITLE
Dunning for both brands

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#4233]
### What needs to be documented?

- Surface dunning process for Upsun surface level
- Document new process for Platform.sh

### Additional context

- https://docs.upsun.com/administration/pricing.html#dunning-process
- https://docs.platform.sh/administration/pricing.html#dunning-process

**Comment by chadwcarlson** [comment]
Awaiting question:

- dates between brands
- code push in timeline
- org data post dunning retained for how long?

**Comment by FatimaZ09** [comment]
- **Dates:** Traditional Platformsh customers: Projects suspended on the 16th after 3 charge retries (4th of month, 11th of month, 15th of month
- Upsun customers: organization restricted immediately after failed payment; projects and organization suspended on the 12th after 3 charge retries (4th, 6th, 11th); final charge retry and notification at 31st day (10 days before deletion), projects deleted 41 days after initial charge attempt (30 days after suspension).
- New Upsun customers without a successful payment: same as above, but projected deleted on 13th (one day after suspension)
**- Dunning process doesn't check code push**
**- All projects on the billing subscription are deleted following this process. Organizations are suspended in Upsun but NOT in PSH**
