### ISSUE TITLE
Formatting issue in code block on "Serve static sites" page

### ISSUE THREAD

**Issue by hannesvz** [platformsh/platformsh-docs#4258]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/create-apps/web/static.html#create-cache-rules

### What exactly should be updated?

Under the "Conserve the server" section the code block markdown is invalid, causing some strange formatting:

![image](https://github.com/user-attachments/assets/d822d199-b81b-49fa-a70b-2240df887890)

**Comment by chadwcarlson** [comment]
Has been fixed https://docs.platform.sh/create-apps/web/static.html#create-cache-rules. Thanks for reporting!
