### ISSUE TITLE
Drupal Documentation missing/incomplete ?

### ISSUE THREAD

**Issue by jordila** [platformsh/platformsh-docs#454]
In the past we had :

https://docs.platform.sh/drupal/guides/type/php/drupal/setup/get-started.html

now , current Drupal developement in Platform documentation seems to me incomplete/missing ? :

https://docs.platform.sh/frameworks/drupal7/developing-with-drupal.html

**Comment by Crell** [comment]
We decided a while back to drop most of the project-specific guides, as they were 98% redundant with other documentation we already had.  What gaps are there in the Drupal 7 (or Drupal 8 for that matter) sections now that you feel should be covered?  I'm happy to add more detail but I don't want to duplicate information that's already available elsewhere in the docs.

**Comment by jordila** [comment]
Yes @Crell , after a second (and 3rd) reading i noticed what you just mentioned.
The issue was in my side... Now it's done... and not missing what i was missing before the exercise.
