### ISSUE TITLE
Menu items should match page titles

### ISSUE THREAD

**Issue by pjcdawkins** [platformsh/platformsh-docs#619]
There are a few of these inconsistencies, for example:

<img width="629" alt="screen shot 2017-08-04 at 17 54 18" src="https://user-images.githubusercontent.com/1465106/28978535-477927cc-793e-11e7-8ffe-9bbe6dca25c9.png">

**Comment by Crell** [comment]
I don't think they necessarily should be identical in all cases, but that one does seem a mismatch.  They should at least be similar.
