### ISSUE TITLE
The generated custom PHP.ini link on TOC is wrong

### ISSUE THREAD

**Issue by mrkschan** [platformsh/platformsh-docs#653]
On https://docs.platform.sh/languages/php.html, the TOC "`Custom php.ini" link is wrong.

That wrong link is generated as `https://docs.platform.sh/languages/php.html#custom-php.ini`, while the correct one should be `https://docs.platform.sh/languages/php.html#custom-phpini`. Note the `.`.

**Comment by Crell** [comment]
Hrm.  That seems like an upstream bug caused by the period.  We can t
