### ISSUE TITLE
how-it-works in src/readme.md missing

### ISSUE THREAD

**Issue by skorasaurus** [platformsh/platformsh-docs#695]
[src/readme.md](https://github.com/platformsh/platformsh-docs/blame/0ec503176320bb3ea1628a79d0693deeae035ff4/src/README.md#L5) and [the troubleshooting page](https://github.com/platformsh/platformsh-docs/blame/d2a30fcbb414f49b5d4c812d09c664016c4c078c/src/development/troubleshoot.md#L65) both link to a how-it-works.md 

appears to have been broken in https://github.com/platformsh/platformsh-docs/pull/680/commits/e0400b4ea7e2c10867eac75ffacf70eca515003a

**Comment by Crell** [comment]
It's been fixed, thanks.
