### ISSUE TITLE
bz2 is not installed in PHP 7.1

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-docs#739]

**Comment by xtfer** [comment]
> Current platform docs say if you're running PHP 7.1 or later bz2 is enabled by default. I just found that it wasn't on by default in our PHP 7.1 environment. No big deal on our end - I just added it into .platform.app.yaml - but I'm thinking you may want to update your documentation (or update the defaults to match your documentation).

**Comment by Crell** [comment]
I made an internal ticket for this.
