### ISSUE TITLE
Document new robots behaviour

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-docs#765]
Our previous robots.txt block tells search engines "don't try to index this", but still allows links to show up in search engines if some other site links to them.

The new method (which the engines seem to recommend) is to use a meta tag or corresponding header, X-Robots-Tag: no index, which tells them "you can parse me but don't save me". cf:

https://support.google.com/webmasters/answer/93710?hl=en
https://www.bing.com/webmaster/help/how-can-i-remove-a-url-or-page-from-the-bing-index-37c07477
https://yandex.com/support/webmaster/controlling-robot/html.xml

These two techniques are mutually incompatible, as the engine needs to be able to GET/HEAD the page in order to see the header that it should not store the page.

**Comment by Crell** [comment]
Closing in favor of #772.
