### ISSUE TITLE
Add instructions to create new InfluxDB user

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-docs#793]
curl http://<influxdb>/query -F "q=CREATE USER admin WITH PASSWORD '<password>' WITH ALL PRIVILEGES"

**Comment by Crell** [comment]
Context?  Does our service not come with a working user currently?  (If so, that's a bug, not a doc fix.)

**Comment by xtfer** [comment]
I believe it does not. I dont know any more than that.

**Comment by CollierCZ** [comment]
This does not seem to be an issue on the version of the service that we use.
