### ISSUE TITLE
"Fastly" section in "eZ platform" does not redirect anywhere

### ISSUE THREAD

**Issue by mnocon** [platformsh/platformsh-docs#845]
Hi!

On the main doc page: https://docs.platform.sh it is possible to expand the "eZ Platform" category (it contains a single item: "Fastly"). Clicking it does not redirect to any other page (and there is no mention of Fastly in the eZ Platform page) which makes me believe that there is something wrong with the doc navigation.

Best,
Marek

**Comment by andrerom** [comment]
@Crell I guess we missed this during review or something.
