### ISSUE TITLE
Broken links in Table of Contents

### ISSUE THREAD

**Issue by alice-0-kim** [platformsh/platformsh-docs#852]
Hi, I noticed that when the titles contain double quotes, the links in table of contents do not map into the right content.

Example:
```
https://docs.platform.sh/development/troubleshoot.html#http-responses-%22502-bad-gateway%22-or-%22503-service-unavailable%22
```
does not match with
```
https://docs.platform.sh/development/troubleshoot.html#http-responses-502-bad-gateway-or-503-service-unavailable
```

Thanks!

**Comment by Crell** [comment]
Hi Alice.  Thanks for the head sup.

Unfortunately those links are auto-generated and the Gitbook plugin we use isn't handling quotes in section titles properly.  That's an upstream bug with the TOC plugin, so until that gets fixed we're kind of stuck with it.  (Or trying to weasel around it by changing our section titles, which I've considered.)

**Comment by Crell** [comment]
Related #653
