### ISSUE TITLE
Incorrect `grep` for PHP memory usage analysis

### ISSUE THREAD

**Issue by Kingdutch** [platformsh/platformsh-docs#924]
It looks like the `grep` that you list on https://docs.platform.sh/languages/php/fpm.html#measuring-php-worker-memory-usage doesn’t do what you advertise :yum:

The date that you grep `date +%Y-%m-%dT%H --date='-7 days'` outputs `2018-09-12T09` if I execute that now.

Docs say `This will print out a table of how many requests used how much memory, in KB, over the last 7 days.` 

But it will actually only print out the requests that were made in the current hour 7 days ago (which may not be in the access logs if there are a lot of requests).

**Comment by Crell** [comment]
Thanks, @Kingdutch.  We've updated the command to just pull the last 5000 requests regardless of time.
