### ISSUE TITLE
Update SimpleSAMLPhp documentation

### ISSUE THREAD

**Issue by Berdir** [platformsh/platformsh-docs#965]
https://docs.platform.sh/frameworks/drupal7/simplesaml.html# was useful in setting it up, but I guess most people these days would need a drupal8 version.

It was also missing a crucial piece that took me a while to track down. with the new cookie behavior, you have to explicitly add SimpleSAMLSessionID to the cookies if you have that configured or it will just go into endless loops.

**Comment by Crell** [comment]
Hi @Berdir.  I don't have a SimpleSAML server to test against, unfortunately.  If you have a working D8 config now can you share it with us so I can dissect it into a proper tutorial?  (That's how we got the D7 instructions; another customer was able to test the instructions and give feedback.)

**Comment by Berdir** [comment]
Hey, lost track of this.

I realized that a D8 page already exists and that looks pretty fine, so I think the only issue here is that it would be helpful to document the cookie configuration.

Specifically, I had to do this:

```
      cookies: ['/^SS?ESS/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
```
