### ISSUE TITLE
To make easier to find a entry, SUMMARY.md could be alphabetically ordered

### ISSUE THREAD

**Issue by derrix060** [platformsh/platformsh-docs#974]
While reviewing a PR, I've found very confused how the entries in SUMMARY.md are organized. Currently, there is no order, and for someone that is seeing the documentation for the first time (I'm included), is a little bit difficult to know it a specific server or app is supported.

I think ordering alphabetically would make this "search" a little bit easier.

**Comment by demosdemon** [comment]
I see the PR for this was merged so I'm closing this for tidyness sake.
