### ISSUE TITLE
[Improvement] Add spelling checker to CI/CD

### ISSUE THREAD

**Issue by derrix060** [platformsh/platformsh-docs#976]
In order to detect spelling problems, nothing better than a machine. We don't expect to have a software that will know every word, slang and technical terms, but usually is possible to create a kind of "dictionary" for these words.

A perfect spelling is essential for a documentation repository, like this. Good option are: [yaspeller](https://github.com/hcodes/yaspeller) and [markdown-spellcheck](https://www.npmjs.com/package/markdown-spellcheck) but any tool will be good enough.

**Comment by Crell** [comment]
Most people have a spellchecker built into whatever editor they're using, even if that's a browser at this point.  Thanks for the suggestion, though.
